### ISSUE TITLE
Location of engine version in UA string depends on Firefox compat, not Gecko compat

### ISSUE THREAD

**Issue by libertyernie** [MoonchildProductions/Pale-Moon#466] opened 2016-07-25 01:11 UTC
Pale Moon has two config options for the UA string (that I know of):

- general.useragent.compatMode.firefox controls the presence of the Firefox/##.# token in the user agent string
- general.useragent.compatMode.gecko controls the presence of the Gecko/20100101 token in the user agent string

general.useragent.compatMode.firefox, when enabled, also replaces the Goanna version number after "rv:" with the Gecko/Firefox version, and moves the Goanna version to the "Goanna/..." token. However, If the "Gecko/" string is still present, some web sites checking to warn users if their browser if out of date (especially if they were built [specifically to look for Gecko, not Firefox](https://wiki.mozilla.org/User:Sardisson/Gecko_is_Gecko)) will assume that the version number of "rv:" is the Gecko version, which is incorrect.

I think it would make sense for the "rv:" number to be controlled by general.useragent.compatMode.gecko instead, so that the number would represent the equivalent Gecko version when Gecko compatibility is enabled, and the Goanna version when it is not.

I can create pull requests for both this project and Tycho if you think this makes sense.

**Comment by wolfbeast** [comment] 2016-07-25 17:29
The problem is that rv: should be the engine version, not a product version.
The Goanna slice should have a build-id with it, not its version.
The Gecko slice is a "frozen" compatibility slice and has been for years -- it's only there because the web as a whole still insists on checking for it. Even IE and the likes have "gecko" somewhere in it to indicate general feature compatibility and to not break a broken UA-sniffing web.

What you suggest leaves no room for a Goanna slice with a build id in all practical use (because nobody wants to disable the Gecko slice). Our engine version will be the platform version which belongs in rv: -- not the product compatibility version. Then you'd be assuming we'd always want to lie about our platform with some arbitrary number.
See also: http://forum.palemoon.org/viewtopic.php?f=24&t=9077
Changing this again after not even a year has passed seems like a pretty bad idea to me.

**Comment by libertyernie** [comment] 2016-07-25 17:34
I am OK with the Goanna version number being in "rv:". But why does having Firefox compatibility on affect the version number after "rv:"? Shouldn't that number always reflect the platform, not the product?

**Comment by wolfbeast** [comment] 2016-07-25 17:37
Mozilla has made rv: and Firefox/nn (plaform and product) equal in their UA. As a result, sites WILL check for `Firefox/` and then go and check the Firefox version with `rv:` -- Like I said blurring the lines between platform and product.

I don't have any data about how many sites still do this in 2016, but I gather a good number. I'd prefer not to touch `rv:` myself as well, but it has been needed before.

**Comment by wolfbeast** [comment] 2016-07-25 17:42
@mattatobin Can you give some input here? What do you think is wise for v27? Should we properly advertise the platform at all times from then on? I kind of lean towards that change but I'd like your input.

**Comment by LimboSlam** [comment] 2016-07-25 19:34
If it helps you guys, I have my whole family running the UA string of the plaform and product version Pale Moon/Goanna. Yeah no Firefox/Gecko whatsoever in the UA string other than the ones provided by default in about:config. 

And so far so good for these past couple of months.

**Comment by mattatobin** [comment] 2016-07-25 20:48
Hmm.. Perhaps we should not have a separate Gecko compatibility pref.. Just make it either we lie and pretend to be Firefox compatible.. or we don't

Firefox Compatibility On: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.9) Gecko/20100101 Goanna/3.0 Firefox/45.9 PaleMoon/27.0.0

Firefox Compatibility Off: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:3.0) Goanna/20160725 PaleMoon/27.0.0

The mixing and matching and the fact that there is no GUI checkbox for Gecko compatibility and even if there was this sort of confusion would continue..

Also, I think the "Firefox Compatibility Mode" text should be changed to better reflect what it actually does.. People are always asking "What does this do" or "Does this apply to extensions" or other such questions that need constantly answered by us.

MAYBE a better UI control would use a drop down box. with a label with the text
"User Agent Mode:" with the drop down options being "Firefox Compatibility" and "Native"

Maybe even add a custom option that can control the pref general.useragent.override since many many users seem to love to change their global UA anyway.

**Comment by MoonChild** [comment] 2016-07-25 21:57
I'm not the MoonChild You are looking for!

**Comment by wolfbeast** [comment] 2016-07-26 09:16
@mattatobin If you recall when Goanna was in prerelease we removed the Gecko/ slice and it caused no end of trouble. And we are "like gecko" even if we are based on Goanna since they are close forks. I don't want a repeat of that -- I want to FIX web compatibility with Tycho, not recreate it.

**Comment by wolfbeast** [comment] 2016-07-26 10:08
How about the following idea, if we're going to have a drop-down anyway:
"Firefox Compatibility": rv=compat, Gecko/ present, Firefox/ present, Goanna/version
"Generic Gecko": rv=compat, Gecko/ present, Goanna/version (no Firefox/)
"Native": rv=version, Goanna/buildID (no Firefox/, no Gecko/)

Native would be the default.

**Comment by mattatobin** [comment] 2016-07-26 10:42
That makes sense... Default should likely be Generic Gecko (could use better text than Generic Gecko) because I doubt detection scripts have changed that much and only one I know of accounts for us.

**Comment by libertyernie** [comment] 2016-07-26 13:45
Looks OK to me. I suppose if websites are going to balk at an unknown browser, it's probably better they think you're an old Gecko than no Gecko at all.

**Comment by MoonChild** [comment] 2016-07-26 16:41
Remove my emailadres. I'm not with MoonChild Production!

**Comment by mattatobin** [comment] 2016-07-26 18:47
Use the unsubscribe link.. Also sorry for the confusion..

**Comment by wolfbeast** [comment] 2016-07-26 19:32
There's no single solution for the different broken UA sniffing methods out there. If they insist on doing so anyway then they'll by default get a Gecko version that never existed (3.0 at the moment because of Goanna being 3.0 in the milestone) which should already raise a flag ;)

Of the "gecko checkers" many don't check the version, it seems, anyway. But will break if it's a completely unknown engine.

**Comment by wolfbeast** [comment] 2016-09-01 13:27
This has been addressed in Tycho in several commits with a three-state compatmode setting as a result.
If people need more control than that, there's UA overrides (global&site-specific)

Closing this as solved.

**Closed by wolfbeast** 2016-09-01 13:27 UTC
Labels: Tycho-task
