### ISSUE TITLE
Can't restore browser after minimizing

### ISSUE THREAD

**Issue by zorglub94** [MoonchildProductions/Pale-Moon#809] opened 2017-01-05 15:53 UTC
HI,
Palemoon 27.03 x 64
When I reduce the browser in the taskbar it does not restart and I have to close it and restart

**Comment by wolfbeast** [comment] 2017-01-06 14:32
Please be more specific.
- What OS are you running on?
- What do you mean with "reduce the broser in the taskbar"
- What do you mean with "does not restart"?

If possible, please provide exact steps to reproduce the problem.

**Comment by zorglub94** [comment] 2017-01-06 16:55
I'm running on windows 10

I contiue in french: quand j'appuie sur  le trait horizontal pour 
réduire la fenetre de palemoon dans la barre des taches,il se fige je ne 
peux plus l'agrandir et   je dois le fermer et le redémarrer

google trad:
When I press the horizontal line to reduce the palemoon window in the 
task bar, it freezes I can not enlarge it again and I have to close it 
and restart it

I hope you understand my problem now

**Comment by wolfbeast** [comment] 2017-01-16 20:22
My french isn't good enough, sorry.

OK, so if you minimize the browser it locks up. I can't reproduce that locally.
Are you using any specific tools to change the way windows are handled? Any skinning tools or productivity tools that do anything with window frames?
Are you using any extensions?

**Comment by Atavic** [comment] 2017-02-11 19:36
@zorglub94 do you have some addons installed?

**Comment by KozakIvan** [comment] 2017-02-14 08:41
Why no support for Fetch API JS if based on firefox 45. My Palemoon v27.0.1

**Comment by wolfbeast** [comment] 2017-03-13 21:22
@zorglub94 Could you please see if you can answer our questions? Without more information there's no way forward.

**Comment by wolfbeast** [comment] 2017-05-04 11:26
Closing this as incomplete since no further response was given.

**Closed by wolfbeast** 2017-05-04 11:26 UTC
Labels: Incomplete, More Info Needed
