### ISSUE TITLE
Building 25.7_release on FreeBSD

### ISSUE THREAD

**Issue by RainbowHackerHorse** [MoonchildProductions/Pale-Moon#168] opened 2015-09-12 13:19 UTC
I've been attempting to get Pale Moon building on FreeBSD, both in an attempt to replace FF on my personal laptop, and in an attempt to get it accepted into the FreeBSD Ports tree.

Thus far, I've been using a script I wrote to bootstrap the build environment in a clean FreeBSD jail, to ensure the least amount of environmental conflicts. The script is by no means clean and does some nasty destructive stuff to the OS install currently (but it won't be needed if I can get the build into the ports tree anyway).
If anyone's interested in seeing what I'm doing: https://github.com/RainbowHackz/Moonstrap/tree/Moonstrap-0.8 
(I've got bits in there for CentOS and non-AUR Arch building as well, because why not?)
I've gotten it to the startup cache precomp stage.
Build output is linked below.
https://gist.github.com/RainbowHackz/879694bb6cfc4043168a

I'm using autoconf 2.13 and GCC 4.7. Build and runtime deps I've installed are listed in the moonstrap.sh script in my previous link.

I'm opening this issue on the advice of Trava90, who stated "I'm guessing this is related to commit 940234a (but not 100% positive)"

**Comment by wolfbeast** [comment] 2015-09-12 14:01
> I'm opening this issue on the advice of Trava90, who stated "I'm guessing this is related to commit 940234a (but not 100% positive)"

Well it's related insofar as that that commit re-enables precompilation of the startup cache to be put into omni.ja - the root cause is that the precompilation fails on BSD. For the time being that can be disabled/worked around by adding another conditional in the packager script there based on a BSD-specific define (on line 353).

**Comment by Axiomatic-** [comment] 2015-09-12 23:14
I have gotten Pale Moon to build with OpenBSD which uses GCC, though I had some hiccups on the way though those are strictly due to the compiler. I also have gotten Bitrig which used Clang 3.4 to build Pale Moon as well no problems there either. Never have I encountered the error you get. I suggest you try Clang 3.4, and see if that works, if it does I have a hunch on what the cause of the issue is. Would you kindly please post the full log?

**Comment by RainbowHackz** [comment] 2015-09-13 12:06
Clang from BASE (which I believe is 3.4) does not build. It errors out during the configuration stage. 
I'll see if I can post the complete buildlog in a bit.

**Comment by wolfbeast** [comment] 2015-10-08 15:35
The merged-in patch should provide a suitable workaround. The only thing that does need to be investigated sometime in the future is if this could be solved at the root instead of simply disabling precompilation altogether. It may negatively impact use of the browser on BSD.

**Comment by trav90** [comment] 2015-12-29 08:38
I've been looking into this, and from what I've been able to research so far it appears to be a compiler problem (likely with an optimization option) on some systems, depending on the compiler version and flags in use (making it difficult to reproduce).

**Comment by wolfbeast** [comment] 2016-09-20 23:43
Closing this - from what I've heard recently there isn't much of an issue building on BSD as long as a proper `.mozconfig` is used.

**Closed by wolfbeast** 2016-09-20 23:43 UTC
