### ISSUE TITLE
Palemoon v27.6.1 crashes

### ISSUE THREAD

**Issue by Gpower2** [MoonchildProductions/Pale-Moon#1476] opened 2017-11-17 09:38 UTC
I experienced a crash after updating to v27.6.1 and after some time browsing.

The unhandled exception message:
Unhandled exception at 0x00007FF90E8BA68C (xul.dll) in palemoon.exe: 0xC0000005: Access violation reading location 0x0000000000000000. occurred

The stack trace with Visual Studio is:

	xul.dll!00007ff90e8ba68c()	Unknown	No symbols loaded.
 	xul.dll!00007ff90e8cdfb5()	Unknown	No symbols loaded.
 	xul.dll!00007ff90f6a97d7()	Unknown	No symbols loaded.
 	xul.dll!00007ff90f6a8b7f()	Unknown	No symbols loaded.
 	xul.dll!00007ff90f6a88ab()	Unknown	No symbols loaded.
 	xul.dll!00007ff90f6b5ef3()	Unknown	No symbols loaded.
 	xul.dll!00007ff90f6b5f1e()	Unknown	No symbols loaded.
 	xul.dll!00007ff90f6b445b()	Unknown	No symbols loaded.
 	xul.dll!00007ff90f6b49bd()	Unknown	No symbols loaded.
 	xul.dll!00007ff90faaae39()	Unknown	No symbols loaded.
 	xul.dll!00007ff90fa9fd58()	Unknown	No symbols loaded.
 	xul.dll!00007ff90e8b0b17()	Unknown	No symbols loaded.
 	xul.dll!00007ff90e8cd7a1()	Unknown	No symbols loaded.
 	xul.dll!00007ff90ea83b2a()	Unknown	No symbols loaded.
 	xul.dll!00007ff90ea6e6bb()	Unknown	No symbols loaded.
 	xul.dll!00007ff90faaac58()	Unknown	No symbols loaded.
 	xul.dll!00007ff90fae4f73()	Unknown	No symbols loaded.
 	xul.dll!00007ff90ffde563()	Unknown	No symbols loaded.
 	xul.dll!00007ff910001870()	Unknown	No symbols loaded.
 	xul.dll!00007ff9100003c6()	Unknown	No symbols loaded.
 	xul.dll!00007ff9100025e6()	Unknown	No symbols loaded.
 	palemoon.exe!00007ff68fd01b21()	Unknown	No symbols loaded.
 	palemoon.exe!00007ff68fd01688()	Unknown	No symbols loaded.
 	palemoon.exe!00007ff68fd01e4c()	Unknown	No symbols loaded.
 	palemoon.exe!00007ff68fd02a54()	Unknown	No symbols loaded.
 	[External Code]		Annotated Frame

Unfortunately it was so sudden I don't know how to reproduce it.
Hopefully the stack trace can reveal something to you.
You can close the issue if you think it doesn not contain enough information.

**Comment by wolfbeast** [comment] 2017-11-17 09:57
Please include an appcrashview report.

**Comment by wolfbeast** [comment] 2017-11-24 11:55
Likely duplicate of #1493

**Closed by wolfbeast** 2017-11-24 11:55 UTC
Labels: Duplicate
