### ISSUE TITLE
Update libvpx to 1.6.x?

### ISSUE THREAD

**Issue by roytam1** [MoonchildProductions/Pale-Moon#1439] opened 2017-11-01 11:47 UTC
Firefox has updated their bundled libvpx to 1.6.0, see https://bugzilla.mozilla.org/show_bug.cgi?id=1223692

I wonder if palemoon will follow as well?

**Comment by janekptacijarabaci** [comment] 2017-11-01 11:53
Dupe of #547.

**Closed** 2017-11-01 13:02 UTC
Labels: Duplicate
