### ISSUE TITLE
Tabs on top always resize immediately

### ISSUE THREAD

**Issue by Munkenmo** [MoonchildProductions/Pale-Moon#384] opened 2016-03-07 07:13 UTC
_browser.tabs.resize_immediately = False_ has no effect when _browser.tabs.onTop = True_

[Relevant Thread](http://forum.palemoon.org/viewtopic.php?f=3&t=11419)

[Video](https://vid.me/Ihh9)

**Comment by wolfbeast** [comment] 2016-03-07 10:18
I'm unable to reproduce this issue. The tabs don't resize immediately with tabs on top in either windowed or maximized mode, as is appropriate.

**Comment by Munkenmo** [comment] 2016-03-07 10:42
I can reproduce this in a new profile.

Something else I've just noticed though, I can only reproduce it when the browser is maximised.

**Comment by wolfbeast** [comment] 2016-03-07 11:13
Like I said I've tested this in maximized mode as well; I cannot reproduce this. Tabs do not re-size immediately when I close them.

Videos aren't very useful here since they don't show what kind of input is used to close tabs etc. Please provide exact steps you use to reproduce this issue.

**Comment by Munkenmo** [comment] 2016-03-07 11:23
Windows 7 Ultimate, Pale Moon version 26.1.1 x86

Steps I did in the video:
1. create profile: New User
1a. Launch browser under New User profile.
2. left clicked Pale Moon forum button a bunch to open tabs
3. use middle mouse button to close tabs.
4. change tabs to be on top, via Pale Moon menu
5. left clicked Pale Moon forum button a bunch to open tabs
6. use middle mouse button to close tabs.
7. maximize browser window
8. left clicked Pale Moon forum button a bunch to open tabs
9. use middle mouse to close tabs.
10. as you can see, the tabs are resizing immediately.
11. show settings in about:config
12. show addon / extension settings


Sorry if that's over the top, and sorry that my videos aren't useful, I'm fairly new to bug reporting and didn't know a better method of displaying the bug.

**Comment by wolfbeast** [comment] 2016-03-07 11:51
I played around with it some more, initially still couldn't reproduce, but it seems to be a specific combination:

- tabs overflow
- the overflowed tab strip is scrolled all the way to the first tab
- tabs are on top
- tabs are drawn in the title bar

This is tied to the algorithm in use to balance closing tabs on a strip when tabs are in the middle (slide in from left or right), to best adjust for maximum tab visibility. This is a tricky question. Not a bug per se since it's working as designed, but the side effect of sliding in from the left when you are left-most is that the tabs resize. I don't see an easy solution here.

If anyone else has some ideas, I'm open to them :)

**Comment by wolfbeast** [comment] 2016-03-07 11:58
Actually, this may be tied to the overflow not cancelling out in this situation which has already been reported. I just need to see with a build that fixes it, if this gets fixed at the same time.

**Comment by wolfbeast** [comment] 2016-03-08 18:28
It's closely related but a separate issue, I think I have a solution for this particular problem though.

**Closed** 2016-03-08 18:34 UTC

**Comment by wolfbeast** [comment] 2016-03-10 14:06
Workaround reverted in lieu of a styling solution that was at the root of it.
