### ISSUE TITLE
Riot.im Does Not Work Properly, "Incomplete API"

### ISSUE THREAD

**Issue by benrob0329** [MoonchildProductions/Pale-Moon#1551] opened 2017-12-19 18:49 UTC
Riot.im (https://riot.im/app) does not display properly, the developers stated that Pale Moon has an incomplete "code copy" API, which means that it passed the feature check but doesn't work properly.

More information can be found in [this](https://github.com/vector-im/riot-web/issues/5778) issue.

**Comment by wolfbeast** [comment] 2017-12-19 22:16
Please indicate exactly which API is supposedly incomplete? Provide a link to the spec/standard?

**Comment by benrob0329** [comment] 2017-12-20 01:22
Judging from ```TypeError: _reactDom2.default.findDOMNode(...).querySelectorAll(...).forEach is not a function``` I would say some modern JavaScript functions.

I'll try to get the minimum version of JS required for the site, and report it here.

**Comment by wolfbeast** [comment] 2017-12-20 14:13
That's the same problem we've seen on a mongodb blog site. I'm guessing someone decided to update their framework with incompatible JS. 
This isn't supported by IE, Edge or us -- Only very recent incarnations of Chrome and Firefox support this.

QuerySelectorAll() spits out a NodeList. NodeLists are not arrays so they need special treatment; this isn't a problem with JS but rather DOM handling. we don't support forEach() on NodeLists; the framework in use on that site should make sure to use e.g. Array.from() on the result of QuerySelectorAll() to be browser agnostic, and not use shinies from living "standards" unless they are confirmed to be supported across the board.

**Comment by wolfbeast** [comment] 2017-12-20 14:14
Duplicate of #1546

**Closed by wolfbeast** 2017-12-20 14:14 UTC
Labels: Duplicate
