### ISSUE TITLE
Location bar suggests too much

### ISSUE THREAD

**Issue by sergeevabc** [MoonchildProductions/Pale-Moon#740] opened 2016-12-03 09:10 UTC
7x64, PM 27.0.2

1. Open Options-Privacy-Location bar and set [Bookmarks].
2. Type something in location bar, it still uses history to make suggestions.

**Comment by wolfbeast** [comment] 2016-12-06 13:41
Looks like a dumb typo >.<

**Comment by wolfbeast** [comment] 2016-12-06 14:14
Actually, no, it's correct (enabled/disabled is returned which gets put into the pref when writing the behavior value)
Needs some more research why `browser.urlbar.default.behavior` is ignored.
This worked in v26.*, correct?

**Comment by sergeevabc** [comment] 2016-12-06 15:03
> This worked in v26.*, correct?
Yes.

**Comment by wolfbeast** [comment] 2016-12-06 15:26
OK thanks, marking as regression.

**Comment by wolfbeast** [comment] 2016-12-06 15:34
Tycho toolkit refactoring issue.
Previous prefs are no longer used -> `browser.urlbar.suggest.*` is the new color.
_Cue Wizard of Oz music_

**Closed** 2016-12-06 17:06 UTC
Labels: Bug, Regression
