### ISSUE TITLE
26.2.0 breaks keyboard navigation of menus

### ISSUE THREAD

**Issue by agilbertson1977** [MoonchildProductions/Pale-Moon#415] opened 2016-04-05 17:51 UTC
Copy from the forum to here for maximum visibility:

by hvdijk » Tue Apr 05, 2016 12:07 pm
Steps to reproduce the problem:
- Start Pale Moon.
- Press Alt+F.
- Press the Down arrow key.

Expected result:
- The File menu's second menu item is selected.

Actual result:
- The File menu's first menu item remains selected.

It's not working with other keys either. This happened to me after upgrading to Pale Moon 26.2.0. Re-testing with the portable versions shows it's still working in the 26.1.1 version, and broken in the 26.2.0 version, both with a completely clean profile. Specifically:

Operating System:
- Windows 10 Pro Insider Preview. Can repeat the test later on plain Windows 10 Pro if required.
Pale Moon versions:
- Palemoon-Portable-26.1.1.win64.exe works
- Palemoon-Portable-26.2.0.win64.exe doesn't work

Given that big changes of this version are in the keystroke handling, it makes sense for this problem to be linked to the new version.

Also confirmed to be present on Windows 7 Enterprise Edition using x86 version and Linux Mint 17.3 (also x86).

**Comment by THEtomaso** [comment] 2016-04-05 18:16
Also copied from the forum:

Confirmed.
I just noticed that hotkeys doesn't work for navigating my bookmarks anymore.

**Comment by wolfbeast** [comment] 2016-04-05 20:07
I'll give this top priority. Sorry that it slipped through our beta testing cycle into release.

**Comment by wolfbeast** [comment] 2016-04-05 21:43
Documented as a known issue on the website.

**Comment by trav90** [comment] 2016-04-06 02:03
I can verify that commit d166e19 ewsolves the issue for me.

**Comment by janekptacijarabaci** [comment] 2016-04-06 07:03
This is also the place where beta versions will be?
http://www.palemoon.org/WIP/

I see nothing here, too...
ftp://ftp.palemoon.org/Pale_Moon/26.x/beta/

**Comment by wolfbeast** [comment] 2016-04-06 07:12
Betas usually aren't public, this is tested by our own beta tester team.
It's needed to do it this way because most people don't understand what it means to use a beta version or what beta testing is beyond "early access" or "first!", and we simply can't handle the resulting support request flow.

**Comment by wolfbeast** [comment] 2016-04-06 07:16
Verified fixed, closing this issue.

**Closed by wolfbeast** 2016-04-06 07:16 UTC
Labels: Bug, Critical
