### ISSUE TITLE
27.0.0 build fails with binutils 2.27

### ISSUE THREAD

**Issue by biopsin** [MoonchildProductions/Pale-Moon#712] opened 2016-11-24 22:27 UTC
Heyah,
I'm building on x86_64 Linux with gcc 4.9.4 (glib) and binutils 2.27 and got stuck on
> ld: ../../xpcom/components/nsComponentManager.o: relocation R_X86_64_PC32 against protected symbol `end_kPStaticModules_NSModule' can not be used when making a shared object

[patched](https://bugzilla.mozilla.org/show_bug.cgi?id=1242901) to resolve it for now.

**Comment by wolfbeast** [comment] 2016-11-24 22:44
Duplicate of #704

**Closed by wolfbeast** 2016-11-24 22:44 UTC
Labels: Duplicate
