### ISSUE TITLE
ZType hangs

### ISSUE THREAD

**Issue by alaviss** [MoonchildProductions/Pale-Moon#1047] opened 2017-04-21 16:26 UTC
Upon destroying the big ship in stage 4 of [ZType](http://zty.pe), the tab containing ztype hangs. The browser remains responsive

**Comment by janekptacijarabaci** [comment] 2017-04-21 18:40
Not confirmed (PM 27.2.1):

![1](https://cloud.githubusercontent.com/assets/2373486/25291544/c3f246da-26d2-11e7-9743-cedbb1e1fc54.png)

**Comment by joey04** [comment] 2017-04-22 20:22
Cool game! But like janek, it doesn't hange for me either on 27.2.1, and I've gone well past Wave 4 a couple times now.

Could be an extension causing the problem. What extensions are you running?

**Comment by alaviss** [comment] 2017-04-23 00:24
This issue is happening with my own PM build on Linux. I also don't think extensions are causing problem, as the issue also happens with a new profile. I will try to use the official PM build to see if this issue persist

**Comment by wolfbeast** [comment] 2017-04-23 08:57
If this is your own build then it may be caused by your configuration or compiler in use. Please do check with the official binaries.

**Comment by alaviss** [comment] 2017-04-24 12:46
Same thing happens with official binaries. However the bug doesn't show up on my Windows

**Comment by janekptacijarabaci** [comment] 2017-05-01 20:31
__Last bad: 45.0a1 (2015-12-02)__
Built from https://hg.mozilla.org/mozilla-central/rev/470f4f8c2b2d6f82e56e161a4b05262c85f55b59

__First good: 45.0a1 (2015-12-03)__
Built from https://hg.mozilla.org/mozilla-central/rev/31fc97d173b3e3da5de35d54018855e6c905787e

Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=470f4f8c2b2d6f82e56e161a4b05262c85f55b59&tochange=31fc97d173b3e3da5de35d54018855e6c905787e

**Comment by h1z1** [comment] 2017-05-14 05:03
Interesting game.  I could duplicate the crash but I have no idea why.  It worked a few times then progressively kept crashing more often.  Nothing really stands out in the console, some error about sprites?

```

GET 
http://zty.pe/media/music/orientation.ogg [HTTP/1.1 304 Not Modified 1ms]
uncaught exception: Failed to load resource: media/sprites/plasma.png <unknown>
uncaught exception: Failed to load resource: media/fonts/avenir-18-white.png <unknown>
uncaught exception: Failed to load resource: media/background/gradient.png <unknown>
uncaught exception: Failed to load resource: media/background/grid.png <unknown>
GET 
http://zty.pe/media/music/endure.ogg [HTTP/1.1 206 Partial Content 1ms]
GET 
http://zty.pe/media/music/orientation.ogg
```

Version: 27.3.0a1 (64-bit) (2017-04-16)

Initially it worked, I got the end of round screen and could click back to the menu.  Once it crashed though it was random.  Occurred during the round too.  Animations stop but the sound continues.    Never had problems with other webgl sites.

**Comment by alaviss** [comment] 2018-03-23 17:12
I found a walkaround would be to build palemoon with `--enable-skia` and switch the canvas backend to `skia`

    gfx.canvas.azure.backends = skia

**Comment by wolfbeast** [comment] 2018-03-24 00:30
Using Skia and having it enabled for canvas is the browser default. If your build doesn't use that default set of preferences, then I'm afraid it's your own doing.

**Comment by alaviss** [comment] 2018-03-24 00:43
@wolfbeast I'm afraid it's not the case for Linux

https://github.com/MoonchildProductions/Pale-Moon/blob/0346da39ef01999aee237bfae6b9acc239ace20b/modules/libpref/init/all.js#L690

**Comment by wolfbeast** [comment] 2018-03-24 13:24
Hmm.. I wonder why this was never enabled on Linux then.

**Comment by wolfbeast** [comment] 2018-03-25 09:29
I've done some preliminary testing enabling skia on one of the most tricky Linuxes (Slackware 14) and haven't seen any hangs, so it's probably good enough to use on *nix.

**Comment by trav90** [comment] 2018-03-25 13:35
I also can reproduce the hang on official 27.8.2 builds. I will push out a new unstable build later today for people to test skia.

**Comment by janekptacijarabaci** [comment] 2018-03-26 03:54
Confirmed fix (IMHO).

**Comment by trav90** [comment] 2018-03-26 18:18
@alaviss can you see if this is still reproducible with the latest Linux unstable build?

**Comment by trav90** [comment] 2018-04-05 22:48
I can confirm that this is fixed in the latest unstable. I was able to destroy multiple large ships and reach level 9 with no freezes or hanging of any kind.

**Closed by trav90** 2018-04-05 22:48 UTC
Labels: Linux
