### ISSUE TITLE
Chrome scripts fail when "javascript strict" enforced globally.

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#863] opened 2017-01-28 06:52 UTC
__Steps to reproduce:__
1. Set `javascript.options.strict` to `true`
2. Start the browser and go to (e.g.): `https://www.w3.org/`
3. Inspect the browser console for errors/warnings

At a minimum, I suggest the following:

---

- [x] `ReferenceError: reference to undefined property Ci.nsIWebNavigation.LOAD_FLAGS_URI_IS_UTF8`
/browser/base/content/urlbarBindings.xml:297:14
(see also http://xref.palemoon.org/palemoon-trunk/search?string=LOAD_FLAGS_URI_IS_UTF8)
I don't know if you do not want to return the flag...
See https://bugzilla.mozilla.org/show_bug.cgi?id=945627

---

- [x] `Reference to undefined property rels.feed`
browser.js:2817:69
in: `if (isValidFeed(link, link.ownerDocument.nodePrincipal, rels.feed)) {`
 
- [x] `ReferenceError: assignment to undeclared variable count`
nsBrowserContentHandler.js:756:4
`ReferenceError: assignment to undeclared variable i`
nsBrowserContentHandler.js:758:9
in:
```
count = cmdLine.length;
for (i = 0; i < count; ++i) {
````

- [x] `ReferenceError: assignment to undeclared variable padshow`
padlock.js:210:6
in: `padshow = position;`

- [x] `TypeError: "OAUTH_SERVER_ERRNO_OFFSET" is read-only`
FxAccountsCommon.js:227:2
in: `this[id] = exports[id];`
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1140627

- [x] `ReferenceError: reference to undefined property this.KEY_LOG_BASE`
GMPUtils.jsm:92:2
in:
```
KEY_LOGGING_LEVEL:            this.KEY_LOG_BASE + "level",
KEY_LOGGING_DUMP:             this.KEY_LOG_BASE + "dump",
```

PR #864

**Comment by wolfbeast** [comment] 2017-01-28 13:39
... what exactly is the problem?

**Comment by janekptacijarabaci** [comment] 2017-01-28 14:07
Ad LOAD_FLAGS_URI_IS_UTF8? Currently there is no problem...

Ad other items: If you do not want to clean up, then nothing happens...

**Comment by wolfbeast** [comment] 2017-01-28 14:32
It's just not clear to me what the problem is.
When do there errors/warnings occur?

**Comment by janekptacijarabaci** [comment] 2017-01-28 14:37
__Steps to reproduce:__
You set `javascript.options.strict` to `true`  in `about:config`.
The (re)start of the browser and go to (e.g.):  `https://www.w3.org/`
Throws a/an warnings/errors in Browser Console...

**Comment by wolfbeast** [comment] 2017-01-28 14:53
Ah. So the problem is enforcing strict mode on all scripts (why are you doing this, exactly?) and then some chrome scripts complain/don't work because they weren't written with strict mode in mind or are using an older ES standard.

**Comment by wolfbeast** [comment] 2017-01-28 14:58
If you list steps to reproduce, next time, please list **all** required steps to reproduce a problem, starting from a default setup. The whole point of STR is that someone else can reproduce the error reliably following those exact steps from a new installation/blank profile.

**Comment by JustOff** [comment] 2017-01-28 15:05
Hmm, I always thought that all native chrome scripts must work properly in strict mode, isn't it so?

**Comment by wolfbeast** [comment] 2017-01-28 15:08
Not necessarily. But it obviously shouldn't break when strict mode for content is enforced -- This is probably as much a problem with how the pref is interpreted (it should only apply to content) as it is with the scripts themselves not taking it into account.

**Comment by janekptacijarabaci** [comment] 2017-01-28 15:09
> Why are you doing this, exactly?

Yes, I know that it is not standard... But it's better to have it repaired (continuously over time). Or is it not? (IMHO)

> list all required steps to reproduce a problem

The first step was in the title. Unfortunately, again, I will try to do it...
Anyway, I'm sorry for the misunderstanding.

**Comment by mattatobin** [comment] 2017-01-28 23:55
Isn't this going to affect extensions as well? Are you purposing this be enabled be default?

**Comment by wolfbeast** [comment] 2017-01-29 02:09
> Isn't this going to affect extensions as well?

Absolutely.

**Comment by wolfbeast** [comment] 2017-01-29 02:22
As for the `LOAD_FLAGS_URI_IS_UTF8` that's currently dead code, and should just be cleaned up in the front-end.

**Comment by wolfbeast** [comment] 2017-01-29 02:24
Opened #865 for the leftover property. Merged the minor fixes.

**Closed by wolfbeast** 2017-01-29 02:24 UTC

**Comment by wolfbeast** [comment] 2017-01-29 02:44
Just to be clear. These are just warnings, right? You weren't specific if they were errors... if they were errors, then script execution would fail, but not in the case of warnings.

They SHOULD just be warnings, according to the XPCShell code I'm looking at, in which case this becomes much less of a concern.
