### ISSUE TITLE
Tiny restored window bug

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#967] opened 2017-03-19 11:11 UTC
Here's a strange bug that I've been aware of since the previous Pale Moon version.
Since it also happens with v27.2.0, I thought it was time to report it..

The issue sometimes occurs when I open this page:
https://www.screamer-radio.com/
Pale Moon will switch from its normal maximized view, to this tiny restored window!:
https://www.mediafire.com/convkey/c966/2l0j99su7qj3w9n6g.jpg

I don't know the exact steps to reproduce this issue, but it seems to happen more often whenever I've visited other sites first, building a certain amount of cache perhaps.

**Comment by wolfbeast** [comment] 2018-06-06 11:53
I've been unable to reproduce any sort of of issue similar to this (and it doesn't seem anyone else has either).
Closing this.

**Closed by wolfbeast** 2018-06-06 11:53 UTC
Labels: Incomplete
