### ISSUE TITLE
Plans on supporting sdk/ui/button/toggle module

### ISSUE THREAD

**Issue by schomery** [MoonchildProductions/Pale-Moon#295] opened 2016-01-08 07:04 UTC
There are a few SDK modules that I believe Pale Moon should support internally. Based on my experience if Pale Moon can implement the toolbar module and all its dependencies like `sdk/ui/button/toggle`, many Firefox hosted addons are going to work with Pale Moon; for instance my Privacy Settings extension: http://firefox.add0n.com/privacy-settings.html

Although it is possible to do all the toolbar manipulation manually, but this is just too much work and having a single solid solution is way better approach.

https://github.com/schomery/privacy-settings/blob/master/src/lib/desktop.js#L6

**Comment by Gitoffthelawn** [comment] 2016-01-20 11:33
+1

**Comment by beerisgood** [comment] 2016-02-06 17:51
That would be awesome!

I assume you make your addon then Pale Moon compatible? :)

**Comment by schomery** [comment] 2016-02-16 11:54
Yes I do

**Comment by mak-66** [comment] 2016-02-16 12:45
Apparently this is needed to make the extension, "Addon Manager with Profiling" work in Pale Moon, so +1 from me for this support.

**Comment by LimboSlam** [comment] 2016-03-18 21:38
@schomery, @Gitoffthelawn, @WagnerGMD, @mak-66, @beerisgood: a bounty as you can see has been labeled for anyone interested who wants to help with this compatibility issue and getting it fixed.

**Comment by Feodor2** [comment] 2016-05-31 11:14
I just finished study the matter. The sdk/ui/button/toggle stuff is just top of the edge. Newer firefox addons are using bootstrab.js and require.js which palemoon has not. Then within the addons code an arrow "=>" statement is used which palemoon js engine is not fully supporting. And that's enough for now.

Will be this "arrow" thing added, and may be many more is what we are to decide. If yes then how we shall do this? If no we are to rewrite addons code and dependancies and shall see how it runs.

**Comment by wolfbeast** [comment] 2016-05-31 11:42
Bootstrapped add-ons (which are not SDK add-ons, by the way) are fully supported. See e.g. our own AdBlock Latitude; that's a bootstrapped add-on.

"require.js" is an API stub in newer add-on SDKs, not necessarily related to this issue since it doesn't have anything to do with the sdk/ui/button module (so if you want to have that available in extensions, it should be put into a different issue to add require.js). It's an incompatibility between add-on SDK versions you'll run into (among others) if you want to just transplant Firefox SDK add-ons to Pale Moon. It doesn't work that way.

Arrow functions `=>` are also supported by Pale Moon (and actually used internally as well). If you find that our implementation of arrow functions isn't complete, then please open a new issue with clear details about what is missing.

**Comment by Feodor2** [comment] 2016-05-31 13:47
Lets clear the goal. It is to do sdk/ui/button/toggle or to do many Firefox hosted addons working?


> Bootstrapped add-ons are fully supported

I mentioned bootstrap.js on which the addon rely in resource://gre/modules/commonjs/sdk/addon/

> require.js is not necessarily related

Yes, but it wont start without it, so i had to invent something, i put older bootstrap.js within addon

> transplant Firefox SDK add-ons to Pale Moon. It doesn't work that way

Then how it does?

> Arrow functions

Why I came to such a conclusion? Yes i found many of that "=>" in the addon sdk code, but they all are inside the comments, so it does not count. Also when i started addon with my bootstrap substitution, i got this:

`WARN addons.xpi: Exception running bootstrap method startup on jid1-CKHySAadH4nL6Q@jetpack: SyntaxError: invalid object initializer @ resource://gre/modules/XPIProvider.jsm`
and  transition to main.js:248
`workers.forEach(w => w.port.emit('changed', {`
As for me I have never seen such expressions within older addons code. This is something new

**Comment by wolfbeast** [comment] 2016-06-01 09:47
See title of this issue. It is to add sdk/ui/button module support. Nothing else.

> Then how it does?

We've been very clear about the fact that SDK add-ons will have to be rewritten/changed for use in Pale Moon.

Arrow functions are fully supported. Your error is because of something else.

**Comment by Feodor2** [comment] 2016-06-09 14:31
I have questions though I'm making some progress with sdk/ui/button, i left aside other things like bootstrap and so, i made addon for testing from mozilla tutorial.

1. Today i read on the palemoon forum that addon sdk may be dropped, so does it make sense to continue work on?
https://forum.palemoon.org/viewtopic.php?f=5&t=12216

2. If we continue on the sdk, than we are to decide what to do with the sdks that palemoon lacks, but the button sdk rely on:
{ required, either, string, boolean, object, number } = require('../../deprecated/api-utils');
{ union } = require("../util/array");
{ isLocalURL } = require('../../url');
I think they can be added as they are without rewriting, and, eventually, it is possible to rewrite them inside the button sdk only.

**Comment by wolfbeast** [comment] 2016-06-09 16:42
Regarding point 1, I don't really see a way that we can continue offering a usable SDK for the next milestone forward, so any work on this would be for our current release versions only.

None of the available SDKs would be compatible with us, because the SDK is a bridge between the front-end and the toolkit/back-end by design. The new milestone will have a disjoint there from an SDK perspective. Older SDKs can talke to our FE, newer SDKs can talk to the BE, but neither can form the bridge it is designed for.

Extension developers currently using the SDK will be forced to rewrite things no matter what they focus on. If they focus on Pale Moon, then native XUL will have to be aimed for. If they focus on Firefox, then a complete rewrite for WebExtensions will be required.

**Comment by mattatobin** [comment] 2016-07-06 10:20
I am declaring this (unless otherwise overruled)..

RESOLVED WONTFIX

**Comment by wolfbeast** [comment] 2016-07-07 19:33
We'll be dropping SDK extension support in the rebase, so this has become a non-issue.

**Closed** 2016-07-07 19:45 UTC
Labels: Extensions, Wontfix
