### ISSUE TITLE
Linux gcc-4.9 builds fail on glibc (libc6) 2.26 

### ISSUE THREAD

**Issue by stevenpusser** [MoonchildProductions/Pale-Moon#1604] opened 2018-01-26 00:18 UTC
Notably, on Ubuntu 17.10 and Debian testing.

The build error is
```

[ 1019s] /usr/src/packages/BUILD/dom/canvas/CanvasRenderingContext2D.cpp:2420:8: error: '__builtin_isfinite' is not a member of 'std'
[ 1019s]    if (!std::isfinite((float)aX) | !std::isfinite((float)aY) |
[ 1019s]         ^
[ 1019s] /usr/src/packages/BUILD/dom/canvas/CanvasRenderingContext2D.cpp:2420:8: note: suggested alternative:
[ 1019s] <built-in>: note:   '__builtin_isfinite'
```

Which is caused by this code in CanvasRenderingContext2D.cpp:
```

  // bug 1018527
  // The values of canvas API input are in double precision, but Moz2D APIs are
  // using float precision. Bypass canvas API calls when the input is out of
  // float precision to avoid precision problem
  if (!std::isfinite((float)aX) | !std::isfinite((float)aY) |
      !std::isfinite((float)aWidth) | !std::isfinite((float)aHeight)) {
    return false;
  }
```

**Comment by janekptacijarabaci** [comment] 2018-01-26 01:08
IMHO: Dupe of #1553.

**Comment by wolfbeast** [comment] 2018-01-26 06:09
Yup, duplicate.
glibc 2.26 is busted. Not our fault.

**Closed by wolfbeast** 2018-01-26 06:09 UTC
