### ISSUE TITLE
You can't remove download item from the floating download pop-up.

### ISSUE THREAD

**Issue by NazcaLine** [MoonchildProductions/Pale-Moon#1225] opened 2017-07-09 08:15 UTC
Clear description of the bug found, with a concise and clear title for the issue:

1. You can't remove a download item SOMETIMES from the floating download pop-up.

Steps to reproduce:

1. Download something and wait until it finishes.
2. You will get download completion animation effect and then press the download toolbar button to open the floating download pop-up.
3. Right-click a download item then choose "Remove from history".

Expected results:

1. That download item would be removed from download history AND the floating download pop-up.

Actual results:

1. That download item wouldn't be removed from download history AND the floating download pop-up.

Version: 27.5.0a1 (32-bit) (2017-07-06)

**Comment by janekptacijarabaci** [comment] 2017-07-09 11:42
Dupe of #630

**Closed** 2017-09-19 13:24 UTC
Labels: Duplicate
