### ISSUE TITLE
Improve fullscreen mode on Windows

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#1769] opened 2020-04-09 20:28 UTC
On Windows (especially Windows 10) the fullscreen mode looks out of place, in a few ways:

1. If tabs are not on top when fullscreen is entered, the window controls are placed on the `#nav-bar` in between other toolbar buttons.

![Placement](https://i.imgur.com/DqWRQTc.png)

2. The above window controls are also in effect on Windows 10, which is incorrect for that OS.

3. In this mode #main-window has a static `background-color`. This worked fine in the Windows 7/8 days, though because we can grab the Windows 10 accent color we should apply it here too.

4. The toolbars in this mode do not respect the `--window-text-color` var and so are not given `brighttext` if required.

I would propose the following:

Windows 7:
![Win7](https://i.imgur.com/79kgXN3.png)

Windows 10 (with an accent color applied):
![Win10 with accent](https://i.imgur.com/uc0tuiX.png)

Windows 10 (without accent color - i.e. default):
![Win10 no accent](https://i.imgur.com/fD0VjQG.png)

Windows 10 (persona):
![Win10 persona](https://i.imgur.com/t7im0ZA.png)

Let me know what you think and I'll send over a patch if you want this.

**Comment by wolfbeast** [comment] 2020-04-10 13:00
The window caption controls being out of order is certainly a bug, so that needs to be fixed. They should always be at the far right.

As for the other suggestions... I don't agree with that. Even if it would align more with windowed use captions the problem is that fullscreen mode is usually focused on limited screen-space use and you don't want those huge win 10 controls taking up 3x the space the minimal controls do. The controls need to be made significantly smaller, and that might possibly not work very well for transparent controls, but maybe you can come up with a compromise?

**Comment by Lootyhoof** [comment] 2020-04-10 13:13
OK, how about this?

![Smaller size](https://i.imgur.com/C0ccyuZ.png)

**Comment by wolfbeast** [comment] 2020-04-10 13:49
Looks fantastic :) I agree with that

**Comment by wolfbeast** [comment] 2020-04-10 18:03
Assuming resolved by #1770

**Closed by wolfbeast** 2020-04-10 18:03 UTC
