### ISSUE TITLE
Some buttons on Github have stopped working

### ISSUE THREAD

**Issue by Symbian9** [MoonchildProductions/Pale-Moon#1662] opened 2018-04-04 03:43 UTC
Version: 27.8.3 (bzipped tarball), x64
OS: MX Linux 17.1 (Debian 9), x86_64

After upgrading Pale Moon from 27.8.1 to 27.8.3 on Github different buttons stop working and look like inactive - if place cursor on it buttons not recognized

As test case try edit any file in repository where you has full write access. I use own repo:

- https://github.com/Symbian9/symbian9.github.io/edit/master/README.md

***

- <kbd>Preview Changes</kbd> button (tab switcher) clickable, **but nothing has happen after click**!

![Preview Changes button](http://i.imgur.com/QSlwjgy.png)
![Preview Changes code](http://i.imgur.com/5Hpl3Fv.png)

***

- <kbd>Commit changes</kbd> **button fully inactive**!

![Commit changes button](http://i.imgur.com/5AQjkoD.png)
![Commit changes  code](http://i.imgur.com/tLcMCMb.png)

**Comment by JustOff** [comment] 2018-04-04 08:55
> After upgrading Pale Moon from 27.8.1 to 27.8.3 

It seems this is just a coincident, and the problem is that GitHub starts using ES6 `class` in the main editor:

```
SyntaxError: class is a reserved identifier editor-bda9e6a440abd06a260ca5bc9875871b.js:1:233802
```

**Comment by mattatobin** [comment] 2018-04-04 09:11
Most of these issues are mere coincident.. But that is off topic.

**Comment by wolfbeast** [comment] 2018-04-04 10:30
*sigh* so.. this means then that github is no longer usable because of class nonsense in JS? well shit.

**Comment by Symbian9** [comment] 2018-04-05 11:07
Just try do all same using ***Waterfox 56.1.0*** browser -- all work well! Hm ...
![Commit changes](http://i.imgur.com/WGBgm01.png)
![Preview Changes off](http://i.imgur.com/qkNSP1M.png)
![Preview Changes on](http://i.imgur.com/c1zD9LO.png)

**Comment by wolfbeast** [comment] 2018-04-05 11:36
@Symbian9 please keep comments restricted to this project's applications. We're aware that ES6 classes are implemented in other browsers.

**Comment by Symbian9** [comment] 2018-04-06 00:43
Got reply  from Github staff (from yesterday I contacted with Github Support via e-mail and sent them link to this issue)

> Hi there,
> 
> Thanks for your reply.
> 
> Unfortunately we're not able to provide much help for the Palemoon Browser, as we only support the browsers listed here:
> 
> https://help.github.com/articles/supported-browsers
> 
> Perhaps you could try making sure you have updated to the latest version of that browser?
> 
> Cheers,
> John (GitHub Staff)
> GitHub Support <support@github.com>

**Comment by JustOff** [comment] 2018-04-06 09:57
@Symbian9, since in their answer they claim that [they still support Internet Explorer 11](https://help.github.com/articles/supported-browsers), you can try to complain that there this function [also does not work](https://caniuse.com/es6-class) and ask to provide shim for `ES6 classes` for both IE11 and Pale Moon.

**Comment by Symbian9** [comment] 2018-04-06 13:02
> you can try to complain

OK, I just sent to Github next message

> Since Github claim that Internet Explorer 11 is supported web-browser:
> 
> https://help.github.com/articles/supported-browsers
> 
> And IE 11 also has no support for ES6 class:
> 
> https://caniuse.com/es6-class
> 
> I ask Github team to provide shim for ES6 classes for both IE11 and Pale Moon.
> 
> Please, fix Github now

**Comment by wolfbeast** [comment] 2018-04-07 06:27
At least you got more of a response than I did because so far they have not replied to me. At all.

**Comment by wolfbeast** [comment] 2018-04-10 21:03
Finally have a response from them. Basically we have to be patient right now as they investigate solutions for MSIE which could also apply to us.

> Thanks for writing in to GitHub Support about problems with accessing GitHub.com using your Palemoon browser.

> I see that our team is currently working on an issue that affects IE11, which they believe is also the cause of the problems that you are experiencing. We'll reach back out once there is some resolution to this issue.

**Comment by wolfbeast** [comment] 2018-04-11 12:40
Resolved by a solution on GitHub's side.

Of note, they will be deprecating the use of MSIE in July 2018 at which point we will likely see the use of non-prototypal constructions return due to the fact that people don't want to learn JS anymore.
Hopefully by that time we'll have a working beta of Pale Moon 28.

**Comment by Symbian9** [comment] 2018-04-11 13:00
> Finally have a response from them.
> ...
> Resolved by a solution on GitHub's side.
> ... 
> ... they will be deprecating the use of MSIE in July 2018... Hopefully by that time we'll have a working beta of Pale Moon 28.

Happy to hear that!

Today Github also reply to me

> Hello there,
> 
> Thanks for your patience while our team worked on this. We've just deployed some changes that should resolve the problem you were experiencing in Pale Moon.
> 
> Please let us know if you have any questions about this or anything else!
> 
> Thanks,
> Steve Guntrip (GitHub Staff) <support@github.com>
> 11.04.2018, 14:08

**Comment by JustOff** [comment] 2018-04-14 05:34
Now they almost completely ruined the site with [async-functions](https://caniuse.com/async-functions) :-1:

**Comment by ThosRTanner** [comment] 2018-04-14 08:33
yeah. 'mark all read' button stopped working - it took me an age to mark all my notifications read

**Comment by mattatobin** [comment] 2018-04-14 11:30
All I can say is we are working as hard as we can on UXP Take 2 specifically the Pale Moon port.. Expect to see it on the unstable branch.. eventually.. Maybe by June if we keep up this pace.. We will see.

Damn Github and every other mainstream framework dumpster diving service.

**Comment by sergeevabc** [comment] 2018-04-14 11:45
Perhaps the issue should be re-opened?

**Comment by wolfbeast** [comment] 2018-04-14 13:56
Reopening this, but it's definitely a Github side problem.
They promise compatibility with MSIE11 (and by proxy, Tycho), yet they keep pushing last-minute Friday-afternoon code changes that haven't been tested on MSIE?

There's more broken than just a few buttons this time around; half their framework doesn't work now. Just because some nitwit wanted to plaster "async" in front of a function because it's trendy and cool.

**Comment by wolfbeast** [comment] 2018-04-14 18:11
Looks like they fixed things again. Please confirm.

**Comment by JustOff** [comment] 2018-04-14 18:12
Works for me.

**Comment by sergeevabc** [comment] 2018-04-14 19:03
@wolfbeast, it works. Thank for clarification, sir.

**Closed** 2018-04-14 23:04 UTC
