### ISSUE TITLE
Binary packages not available in (any?) linux repositories.

### ISSUE THREAD

**Issue by phikal** [MoonchildProductions/Pale-Moon#166] opened 2015-09-10 10:59 UTC
Pale Moon has to be either installed via the install script, binaries or compiling it from source. While the latter is acceptable for "advanced" users, the former two are annoying for anyone who has used Linux for a while. The wonderful part about having a package manager is that all updates are controlled centrally and not via multiple installers, as it uninstalling. As far as I know *only* [arch (and derivatives)](https://aur4.archlinux.org/packages/palemoon/) can install pale moon via the AUR (but these are again not binaries, but compile and install scripts), but for me, and many other users using .deb or .rpm based distributions, there is only the previous methods.

Except if there is an explicit wish from the side of the developers, I believe that packages should be created for the Linux systems - I at least haven't found any previous conversation. I hope I'm not submitting this issue in the wrong place... if yes please tell me, but I wanted to express my annoyance, since, in my case, this is actually the reason that is keeping me from using Pale Moon.

**Edit:** Another thing I failed to find is a Migration tool for Linux. Is it just me not finding it or does it not exist, in which case a script could be written.

**Comment by squarefractal** [comment] 2015-09-10 14:12
* At present we have a shortage of manpower for these tasks to be taken up (creating packages as well as providing the necessary infrastructure for package management).
* There is no migration tool provided for Linux systems.

**Comment by phikal** [comment] 2015-09-10 15:12
@squarefractal If the man power is lacking, I could possibly (try to) work on creating and maintaining the packages for debian-based systems. It's in my personal interest to have a Debian package and I'd love to be able to contribute to the project in some way.

**Comment by squarefractal** [comment] 2015-09-10 17:41
>If the man power is lacking, I could possibly (try to) work on creating and maintaining the packages for debian-based systems

You are re certainly welcome! You may, however, want to first contact Moonchild (wolfbeast) on the forum or via email at moonchild at palemoon.org.

**Comment by trav90** [comment] 2015-09-10 17:56
I would love to be able to supply repo packages for Pale Moon, but I simply do not have the time or resources to create them in addition to the "generic" binary at this time. Anyone who is willing and able to create and and maintain packages are more than welcome to! :)

FWIW, Pale Moon is available in the Puppy Linux, Manjaro, and PCLinuxOS repos and can be installed with those distro's package manager.

> However, LPMO could do with some updates; it's extremely confusing for a newcomer to be able to understand how to install Pale Moon.

@squarefractal, if you have some suggestions please send me a PM on the forum. I'll be all ears!

> You may, however, want to first contact Moonchild (wolfbeast) on the forum or via email

Forum might be best. We will also likely be able to help you if you hit any snags.

**Comment by squarefractal** [comment] 2015-09-10 18:12
@trav90 I'm afraid actually this is more of a problem with the site design and organisation of *.palemoon.org, it's not something one can fix with slight changes to documents.

**Comment by chaoskagami** [comment] 2015-09-10 22:06
@squarefractal 
To migrate a linux profile, you can just copy .mozilla/firefox to .moonchild productions in your home folder, FYI.

That was how I switched from FF at least. It does the whole 'Checking compatibity' dance on startup. I'm not sure if that's the correct solution, but it worked when I did that a year ago ago, and there were no hiccups.

**Comment by tumpio** [comment] 2015-09-13 09:47
> FWIW, Pale Moon is available in the Puppy Linux, Manjaro, and PCLinuxOS repos and can be installed with those distro's package manager.

The full list as far as I know:

in official repos:
- Manjaro
- MX-Linux
- PCLinuxOS
- Puppy Linux

in user repos:
- Arch (AUR)
- Slackware (SlackBuilds.org)

**Comment by chaoskagami** [comment] 2015-09-13 23:39
Keep in mind that AUR isn't a binary package. I believe it still builds from source. Unless it's one of the rare instances where there IS an AUR binary.

Adding to that list, there's also a few ebuilds floating around for Gentoo in NP-hardass's personal overlay (https://github.com/NP-Hardass/np-hardass-overlay), but again, that isn't a "binary" as it builds from source.

**Comment by tumpio** [comment] 2015-09-14 06:45
Yes and I believe they are not directly installable with those distros' package managers either.

From https://www.palemoon.org/contributed-builds.shtml
there is also a PPA for Ubuntu but it is out dated.
and some Open Pandora build.

**Comment by phikal** [comment] 2015-09-14 11:51
I have been looking into [fpm](https://github.com/jordansissel/fpm) to create packages for Debian and Red Hat based systems (and more). All I'd need is to build a binary package, and place a few files in the right directories (maybe man pages?). Can someone link a good resource on building Firefox/Palemoon for production systems? If it works, it could be published for Debian, *ubtu, Mint & co. Systems and Fedora.

**Comment by tumpio** [comment] 2015-09-14 12:46
@phikal have you seen this?
http://linux.palemoon.org/help/build/

**Comment by phikal** [comment] 2015-09-14 12:49
@tumpio so I guess I'd have to run  Cent OS in a VM to compile it? But thanks anyway.

**Comment by tumpio** [comment] 2015-09-14 13:18
Quoting the text from the build instructions:
> The recommendation to use CentOS is purely from the consideration of backward compatibility. If you have no need for backward compatibility, you can use any distro you like.

What this backward compatibility means? linux 2.0? :)
for example for Fedora I don't think it is a requirement.

**Comment by wolfbeast** [comment] 2015-09-14 13:48
Backwards compatibility means that they must be able to run on Linux 2.6 kernels.

Please do not make 3.0(+)-only binary distributions as official. Also, if you want to use pre-built binaries, please use the official ones we build and test as starting point for distro-specific packages or repositories; no need to go through the steps to build your own lacking our normal testing cycles and stability tests (QA) and you can have official branding in that case because they are officially distributed binaries.

Please understand that Official branding can *only* be used in the following situations:
* When the end-user builds from source directly
* When official binaries are used (in re-packaged form but otherwise unaltered)
* When a distribution built by a third party is explicitly approved by me for binary redistribution

In all other cases you can't use our official branding or name. See http://www.palemoon.org/redist.shtml specifically point 8.

**Comment by phikal** [comment] 2015-09-14 13:57
@wolfbeast Ok, I will use the official and tested binaries in order to keep the official name. Before publishing, I will link the packages in this thread.

**Comment by wolfbeast** [comment] 2015-09-14 16:06
@phikal Sounds like a plan!

Apologies if my approach may sound a little restrictive to some FOSS proponents, but I'd prefer to avoid a large number of different officially branded binaries floating about that weren't built&tested by us; if it's not strictly required that someone else makes a build for distribution as binary in a repository, then in principle it shouldn't be done -- this (hopefully) prevents issues introduced by third-party builds that would end up on our plate for support with no way of knowing the cause just looking at the symptoms (compiler bug? config bug? library bug? or actually a code bug?).

I've adjusted the redistribution license with a clarification statement 8a now; please let me know if you have any questions or if something isn't entirely clear as for reasoning.

**Comment by phikal** [comment] 2015-09-14 16:15
@wolfbeast Should the same be done for FoassaMail too?

**Comment by wolfbeast** [comment] 2015-09-14 16:40
Preferably.

**Comment by phikal** [comment] 2015-09-19 13:58
I have finally gotten around to find out how the installer works, and replicated the structure for fpm.
Here is a dropbox link to a .deb package for 25.7.0, x86_64: https://www.dropbox.com/s/n932j9ef52nb49b/palemoon_25.7.0_amd64.deb?dl=0

If it's ok, I will write a script to automate the pacakge creation, and will build and publish it for the systems we discussed.

**Comment by deuiore** [comment] 2015-09-19 15:44
I've been maintaining a [Gentoo overlay](https://github.com/deuiore/palemoon-overlay) for almost a year now.
Gentoo users can simply use `layman -a palemoon` and then `emerge` the version they want.
Recently binary versions of the packages have also been added (thanks to [anupamsr
](https://github.com/anupamsr)), which basically just install the official binaries and move stuff around to make them work properly with Gentoo.

**Comment by phikal** [comment] 2015-09-29 19:26
Here is the script I created (based on the installation script) to use with fpm to create packages: https://gist.github.com/phikal/835936d04642aace1b97. Just use
```sh
./create palemoon-25.7.0.en-US.linux-i686.tar.bz2 deb
```
and `palemoon_25.7.0_i686.deb` will be created (I only tested it on debian, and the instalation worked. Can someone test it for .rpm systems?). The resulting package could be offered on http://linux.palemoon.org/ as a primary installation option, with the older ones as alternatives for other systems.
I hope this worked.

**Comment by Pulfer** [comment] 2016-06-27 15:49
Today I added Pale Moon (with New Moon branding) RPM packages to ROSA Desktop Fresh repositories (with patches for KDE integration - KDE file dialogs, ability to set KDE wallpaper from browser etc).

**Comment by Pulfer** [comment] 2016-06-28 06:18
@wolfbeast BTW, maybe I can you "Pale Moon" branding/name instead of "New Moon" for ROSA Desktop RPM package? So it could be easier for users to find it in a package manager.

1. I changed default homepage to our Linux distribution welcome screen
user_pref("browser.startup.homepage", "file:///usr/share/doc/HTML/index.html");
which redirects to
http://wiki.rosalab.ru/en/index.php/ROSA_Desktop_Fresh_R7

2. I also added patches for KDE Integration (based on OpenSUSE Firefox patches + my additions) because KDE is our main Desktop Environment.

**Comment by Pulfer** [comment] 2016-06-28 11:55
@wolfbeast Another reason why I ask permission to use "Pale Moon" branding is described in #451 (language packs apply it anyway, creating inconsistency between browser interface and desktop icon etc).

**Comment by wolfbeast** [comment] 2016-06-28 13:03
Check to make sure you are in compliance with the redist license[1] before using official branding on your own builds on Linux.

[1]http://www.palemoon.org/redist.shtml

**Comment by Pulfer** [comment] 2016-06-28 13:26
I guess, I'm sure in all license points except except for 8 (as I mentioned above, I changed default startup homepage to the distro homepage and added some desktop environment integration patches). 

Point 10 says that I may ask for approvement from you to distribute Pale Moon with official branding. But it's OK for me if you don't approve it for any reason.

**Comment by wolfbeast** [comment] 2016-06-28 14:06
I looked over the patches and I can't allow official branding on this, sorry.

**Comment by Pulfer** [comment] 2016-06-28 14:18
No problems. :-) I found an easy way to apply "New Moon" branding to language packs so  #451 is not a big deal for me anymore.

**Comment by wolfbeast** [comment] 2016-10-18 02:06
Closing this general information issue - for more discussion about inclusion in Linux repositories please go the the Linux specific board on the forum. https://forum.palemoon.org/viewforum.php?f=37

**Closed by wolfbeast** 2016-10-18 02:06 UTC
Labels: Question
