### ISSUE TITLE
Expression compares a char* pointer with a string literal

### ISSUE THREAD

**Issue by computersalat** [MoonchildProductions/Pale-Moon#1594] opened 2018-01-19 17:44 UTC
Usually a strcmp() was intended by the programmer
[ 1703s] E: palemoon stringcompare /home/abuild/rpmbuild/BUILD/Pale-Moon-27.7.1_Release/toolkit/xre/nsAppRunner.cpp:3597

**Comment by janekptacijarabaci** [comment] 2018-01-19 17:52
Dupe of #1581

**Closed** 2018-01-19 20:06 UTC
Labels: Duplicate
