### ISSUE TITLE
Use "Modern" Settings to change default browser on Win8/Win10

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#158] opened 2015-09-03 19:51 UTC
Currently, making Pale Moon change the default browser will open the Default Programs panel of Control Panel, but ONLY if pressing the "Make Pale Moon the default browser" button in Options; if relying on the popup that appears on browser open, this is blocked by Windows. This is due to [changes in behaviour] (http://blogs.windows.com/bloggingwindows/2015/05/20/announcing-windows-10-insider-preview-build-10122-for-pcs/) in how programs can set defaults in Windows 10. In addition, with Control Panel being slowly deprecated in Windows 10, it would be worth investigating using the "Modern" Settings instead. 

BMO:
[1167294] (https://bugzilla.mozilla.org/show_bug.cgi?id=1167294) - Windows 10 blocks the HTTP handler/default browser application dialog

**Comment by wolfbeast** [comment] 2015-09-04 16:53
Shouldn't be too hard to implement.

**Comment by wolfbeast** [comment] 2015-09-04 23:05
Implemented the bug code (ported across) but it fails on Win10 with:

Timestamp: 2015-09-04 15:57:39
Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIShellService.setDefaultBrowser]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://browser/content/preferences/advanced.js :: gAdvancedPane.setDefaultBrowser :: line 665"  data: no]
Source File: chrome://browser/content/preferences/advanced.js
Line: 667

... not entirely sure why, unless the code in that bug is simply incorrect...?

**Comment by Lootyhoof** [comment] 2015-09-04 23:10
Appears to depend on a couple other bugs, if it helps:

[1170743] (https://bugzilla.mozilla.org/show_bug.cgi?id=1170743) ? Public access seems to be denied to this one.
[1173357] (https://bugzilla.mozilla.org/show_bug.cgi?id=1173357) - Firefox no longer provides an option to make it a default .html browser 
[1179249] (https://bugzilla.mozilla.org/show_bug.cgi?id=1179249) - Firefox no longer provides an option to make it a default .html browser

**Comment by wolfbeast** [comment] 2015-09-04 23:10
Looks like Win8 functionality is as-expected, so the problem is likely in the function to open Windows 10's specific "immersive" application panel.

**Comment by wolfbeast** [comment] 2015-09-04 23:21
Heh. in effect, those two bugs revert to the old behavior.

**Comment by Lootyhoof** [comment] 2015-09-04 23:34
Seems the trail goes a bit further than expected.

[791501] (https://bugzilla.mozilla.org/show_bug.cgi?id=791501) - Default Programs UI should select Firefox by default 
[1184508] (https://bugzilla.mozilla.org/show_bug.cgi?id=1184508) - Remember registry hash for later use on Win8+

**Comment by wolfbeast** [comment] 2015-09-04 23:36
I've backed all of it out. Maybe someone else can look at it because this is too much of a mess that breaks existing behavior.

**Comment by mattatobin** [comment] 2016-10-05 14:37
Since Tycho's ancestor is closer to when this landed in the Firefox... Could this be brought back to Tycho?

**Comment by wolfbeast** [comment] 2016-10-05 21:19
it's actually not that complex to do. Just have a better understanding of the code now. I'll see if I can get it to work.

**Comment by wolfbeast** [comment] 2016-10-05 21:50
Solved by e24b1223095d1050fe4fc8486e38cc17a551719c and 06243531e4dbb6518cdf40a219e2b1559c630ddf

**Closed by wolfbeast** 2016-10-05 21:50 UTC
Labels: Help Wanted
