### ISSUE TITLE
Youtube Flash lag high CPU Palemoon v27.2.1 x64 Linux Debian Ubuntu Linux Mint 

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/Pale-Moon#986] opened 2017-03-31 12:34 UTC
OS: Linux Mint 18.1 x64 Mate-Edition
Version: 27.2.1 x64
Link: [https://www.youtube.com/watch?v=1fRjwBtVNEs&t=0s](https://www.youtube.com/watch?v=1fRjwBtVNEs&t=0s)
Quality: 1080p60
CPU: Intel Core i5-3230M
GPU: Nvidia 710M
Driver: xserver-xorg-video-nouveau v1:1.0.12-1build2

Microstuttering in the video and while scroling the page.
CPU spikes included.
Doesn't the hardware acceleration working properly?
But I'm glad, that most of the time, the sound isn't stuttering!

Facebook has the micro lags, too.

**Comment by wolfbeast** [comment] 2017-03-31 12:54
The NVidia 710M is an entry-level, mobile GPU (with very poor performance). 60fps 1080p may simply be too much for it.

**Comment by MartinX3** [comment] 2017-03-31 13:12
I installed Firefox v52.0.1
I opened the given link from this ticket.
I waited, that the advertising finished.
I set it to 1080p60.
The CPU usage is only the half.
The core speed is at 2.7 GHz instead of 3.0.
No microstuttering. No lagging.

**Comment by wolfbeast** [comment] 2017-03-31 13:14
Any hints given by about:support ?

**Comment by MartinX3** [comment] 2017-03-31 13:17
Which of this massive amount of informations do you want?

**Comment by wolfbeast** [comment] 2017-03-31 13:19
All of it, as text

**Comment by MartinX3** [comment] 2017-03-31 13:19
[Thats the text](https://pastebin.com/MqwWZaiX)
[Thats the raw data](https://pastebin.com/QMgJ8LBy)

**Comment by wolfbeast** [comment] 2017-03-31 13:26
Copying relevant portion to this issue, since pastebin can expire.

````
Grafik
------
 
Geräte-ID: Mesa DRI Intel(R) Ivybridge Mobile
GPU-beschleunigte Fenster: 0/2 Basic
Karten-Beschreibung: Intel Open Source Technology Center -- Mesa DRI Intel(R) Ivybridge Mobile
Treiber-Version: 3.0 Mesa 12.0.6
Vendor-ID: Intel Open Source Technology Center
WebGL-Renderer: Intel Open Source Technology Center -- Mesa DRI Intel(R) Ivybridge Mobile
windowLayerManagerRemote: false
AzureCanvasBackend: cairo
AzureContentBackend: cairo
AzureFallbackCanvasBackend: none
AzureSkiaAccelerated: 0
````

Well, that explains - hardware acceleration is not possible on the Ivybridge Intel component through the generic MESA driver. You're decoding and rendering the video in software ;)
Maybe someone with more Linux background can help you get acceleration going. Kindly go to the forum for assistance with that.
Closing this issue because it's as-expected for software rendering, and not a bug in the browser.

**Closed by wolfbeast** 2017-03-31 13:26 UTC
Labels: Linux, Media

**Comment by MartinX3** [comment] 2017-03-31 13:29
Thanks for the information, but why does it works in the firefox browser?
