### ISSUE TITLE
proxy: SOCKSv5 proxy does not seem to work

### ISSUE THREAD

**Issue by MingcongBai** [MoonchildProductions/Pale-Moon#482] opened 2016-08-16 03:12 UTC
Currently running Pale Moon 26.3.3, and I couldn't seem to connect via SOCKv5 proxy. I have set up a Shadowsocks proxy in order to use censored websites in China, and proxy is set to 127.0.0.1:1080 via SOCKSv5.

The same configuration works on Firefox but not on Pale Moon.

**Comment by wolfbeast** [comment] 2016-08-16 06:51
Is Shadowsocks an https proxy (meaning it accepts tls encrypted connections)?

**Comment by wolfbeast** [comment] 2016-08-16 06:59
Tried to look up the repo code, but the repos are unavailable:

> Removed according to regulations.

I think they must have been doing something really bad.

**Comment by MingcongBai** [comment] 2016-08-16 07:29
> I think they must have been doing something really bad.

Chinese government has done otherwise to them... They have "hidden" their work to the [master](https://github.com/shadowsocks/shadowsocks/tree/master) branch.

> Is Shadowsocks an https proxy (meaning it accepts tls encrypted connections on its proxy port)?

I believe so (as they do have encryption), but I am not actually sure if it's HTTPS.

**Comment by wolfbeast** [comment] 2016-08-16 08:59
It has to be a standard connection if it uses the socks protocol, so it's likely expecting TLS encrypted connection from the browser to the proxy. Can't tell with "hidden work" -- but in that case it's a duplicate of #258

**Closed** 2016-08-17 13:06 UTC
Labels: Duplicate
