### ISSUE TITLE
Error decoding some JXR images

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1659] opened 2018-03-29 19:45 UTC
Based on the [forum report](https://forum.palemoon.org/viewtopic.php?f=3&t=18729), here are [proper JXR images](https://github.com/MoonchildProductions/Pale-Moon/files/1861681/jxrs_meh.com.zip) taken from https://meh.com/ that result to `Image corrupt or truncated` error.

**Comment by wolfbeast** [comment] 2018-03-30 07:33
The library in use is Microsoft's own reference implementation, so I'm not sure why this would happen.

**Comment by wolfbeast** [comment] 2018-03-30 07:57
Looks like the lib has a few small updates in comparison to what we're using. That's probably the cause.
I'll attempt an update.

**Comment by wolfbeast** [comment] 2018-03-30 08:46
OK, so it seems like the jxrlib 1.1 is what people have been using in the wild to generate jxrs which is apparently quite a bit different from the version we have taken from ff-jxrlib's effort.
Our `/image/decoders/nsJXRDecoder.*` is not compatible with the v1.1 lib and needs rewriting for it (it's not sourced in our own code, it was part of Microsoft's effort).

@rhinoduck -- you've done this adaptation last time; do you think you have time to look at what would be needed to bring it up to speed with what people are using as final?

**Comment by JustOff** [comment] 2018-03-30 09:48
Don't you think it's better to disable JXR support until then?

**Comment by wolfbeast** [comment] 2018-03-30 10:34
that depends... how big of an issue is this? just the one site?

**Comment by JustOff** [comment] 2018-03-30 11:18
I doubt that we have a way to know this for sure, so I just think that having something half-broken is worse than not having it at all. 

And, frankly, I do not see any advantages from supporting this format, except to be able to brag about being the only browser that supports jxr and webp at the same time :stuck_out_tongue_winking_eye:

**Comment by mattatobin** [comment] 2018-03-30 12:20
Hate to say but @justoff may have a point.. Really don't see the point in supporting either format other than bragging rights.. Normal jpeg and png are still the dominant formats and most compatible across all browsers..

However, given that, I don't see any reason to bother doing anything special either.. If a resolution isn't forthcoming by the next point release we should flip it off otherwise..

**Comment by rhinoduck** [comment] 2018-03-30 15:10
I may be able to look at some point today or tomorrow (but that doesn't mean I'll resolve within the same time frame). Feel free to disable JXR support in the meantime if that is what you judge to be best; it can always be flipped back on once it behaves in a satisfactory way.

**Comment by wolfbeast** [comment] 2018-03-30 15:11
webp is actually in use in quite a few places - not so much for jxr. For the simple reason that it saves bandwidth and Chrome's 80% overall market share supports it.
And **these formats were not added for bragging rights** -- as seen websites _DO_ use it when support for it is negotiated, or we wouldn't be looking at this issue right now. If it wasn't for the lib being stood on top of its head between the version we have and the version we should be using to support whatever way these smaller images are encoded, it wouldn't have been a problem either. It may still be a small fix, depending on the cause; will have to have a look at the lib's repo to see what's changed.
As-is we still support most of the JXR spec with our current implementation. Flipping it off in 27.9 if no improvement can be made is a good idea, though, to make sure we don't break too much of the web if more sites start adopting these encodings.

**Comment by wolfbeast** [comment] 2018-03-30 15:17
The repo with history of jxrlib is up now at https://github.com/MoonchildProductions/jxrlib

**Comment by rhinoduck** [comment] 2018-03-30 21:40
I tried one of the images, and this is where it gives up.

https://github.com/MoonchildProductions/Pale-Moon/blob/da2e9cdc718461b8fae48fae6f0d2bf878cd5c20/image/decoders/nsJXRDecoder.cpp#L2670-L2681

Judging by the comments, I'd say it's likely that these particular images have been encoded with the buggy version of the lib. Anyway, I'll try to verify, and see if I can bring the workaround back without it having the potential to crash the browser.

**Comment by wolfbeast** [comment] 2018-03-31 08:10
Thanks very much for the research! So ultimately it's an encoding error, then.
Maybe it'd be a better idea, if this can't be worked around without crashyness, to have an explicit error message thrown instead then instead of a generic data error, so website owners can be pointed to it?

**Comment by wolfbeast** [comment] 2018-03-31 09:50
@rhinoduck looking at the code here, what exactly would cause the crashes on incomplete data? Would that be if `GetTotalNumBytesReceived()` is smaller than the offset? If so, then a simple sanity check on the values (and throwing an error if found bad) should be enough to prevent crashes -- although of course the image will be corrupt (because incomplete).

**Comment by rhinoduck** [comment] 2018-03-31 10:07
There are three such places where things have been commented out if you search for the "Let's not do this" comments. All I remember now is that in the original state, going to https://rhinoduck.net/palemoon/github/issues/105/slow/imgout/cloud_lossless.jxr would crash it (the server will stop sending data after 7 kilobytes).

I actually tried uncommenting the bits; it won't end with an error, but it still won't draw the image. Though I am rather tired now, so do not take this piece of information as 100% reliable. Anyway, need to get some sleep; will get back to this later.

**Comment by wolfbeast** [comment] 2018-03-31 10:20
I'll try some things in the meanwhile. I have a good idea how to work around this problem with a simple extra check in 2 places. The third (the actual image plane being wrong) already seems to have a good corrective function that can just be reinstated.

**Comment by wolfbeast** [comment] 2018-03-31 10:50
The actual image plane being wrong does not have a good corrective function; it may need some extra work to deal with incomplete data, but I'm not sure if we should because it is clearly a bug in the encoder there that any "correction" would just be guesswork, as opposed to the alpha plane issue.

The JXELIB error can be corrected without harm, by the looks of it, as long as a sanity check is in place. I've had no problems loading the .jxr files after making the relevant edits, and meh.com also displays the proper imagery.

**Comment by JustOff** [comment] 2018-03-31 11:22
> going to https://rhinoduck.net/palemoon/github/issues/105/slow/imgout/cloud_lossless.jxr would crash it

Neither IE11 nor Edge can display this file, is that a valid jxr file?


> I've had no problems loading the .jxr files after making the relevant edits, and meh.com also displays the proper imagery.

I confirm, well done!

**Comment by wolfbeast** [comment] 2018-03-31 11:39
> Neither IE11 nor Edge can display this file, is that a valid jxr file?

The "slow" test images will never complete. It's been set up to deliberately stall. So it'd be correct that they can't be displayed in any browser.

**Comment by wolfbeast** [comment] 2018-04-02 14:37
I've decided to put this workaround behind a pref and disable it for now, because there's still the very real chance of crashes if a badly encoded image download gets stalled in the alpha plane area (truncated image) and it's not possible to determine after the fact if it's an encoding error or actual truncation.

I'm working with cloudinary to have them look at their on-the-fly encoding of JXR images and fix it.

Considering this closed as it's an encoder bug and we now have a workaround if necessary.

**Comment by wolfbeast** [comment] 2018-04-05 12:25
Some further research shows that the common encoding error is rather specific and can be worked around relatively safely with some adjustments.

I've done some research with debug messaging in the decoder and it turns out that encoded images have an alpha plane bytecount header that is exactly equal to the total file size. That is incorrect, of course. The spec says:

> A.7.30 ALPHA_BYTE_COUNT
> ALPHA_BYTE_COUNT (when present) specifies the quantity of the **alpha plane codestream data** in the file. When ALPHA_OFFSET is present, ALPHA_BYTE_COUNT **shall also be present**.

So if it's either missing or not giving the alpha plane byte count only, then that's an encoding error.
It seems that jxrlib 1.1 suffers from this. Even Microsoft's own Adobe PS plugin when using planar alpha does it wrong :frowning_face:

**Comment by JustOff** [comment] 2018-04-05 13:08
This sounds like we are forced to have some kind of workaround enabled by default ...

**Comment by wolfbeast** [comment] 2018-04-05 13:27
Yes, but thankfully with the encoding error being so specific, there's no real chance of confusing it with a truncated image so crashes can be avoided.

**Comment by JustOff** [comment] 2018-04-05 15:36
I confirm this workaround works pretty well with meh.com images :+1:

**Comment by wolfbeast** [comment] 2018-04-05 15:51
You can confirm the bad encoding with `-console` which will spit out debug messages whenever the workaround is triggered.

**Comment by JustOff** [comment] 2018-04-05 16:13
Yeah, it turns out that even https://palemoon.start.me/start triggers it :confounded:

**Comment by wolfbeast** [comment] 2018-04-10 09:52
Confirmed by Max Rozenoer (Cloudinary Support) that it is an encoding error, even in the reference lib/encoder! They will be looking into patching their JXR encoder to follow the spec and not having this bug -- they will also be offering the patch up to Ubuntu that ships the jxrlib. It's not clear if there is a single maintainer of the lib or who maintains it in that case (since codeplex is just archiving now) but hopefully this fix will be distributed to other copies of the lib.

In the meantime, the workaround in our trunk now will do for improperly-encoded files.

**Comment by wolfbeast** [comment] 2018-04-10 09:53
TODO: remove debug printf() before release.

**Comment by mattatobin** [comment] 2018-04-10 10:09
`#ifndef MOZ_OFFICIAL_BRANDING` maybe?

**Closed** 2018-04-11 10:43 UTC
Labels: Images
