### ISSUE TITLE
JXR breaks LTO builds on GCC (v4,5,6)+Gold

### ISSUE THREAD

**Issue by cofi89** [MoonchildProductions/Pale-Moon#924] opened 2017-02-28 02:45 UTC
Hi,

I'm aware that I'm on my own with this, given that neither LTO nor GCC 5/6 are supported/recommended/warranted to work ( though btw, for me, v6 seems to be producing mostly* stable bins since about 27.0.0b1 ( or b2 ), LTO included ). *I had a single crash since then ( before it was much worse ).
But a report can't hurt...

With that said, it was all smooth sailing until JXR was added. I didn't have time to investigate properly until tonight, so to the point pointed by git point, khm, bisect:  
```
# bad: [203922cfa391a5da64c547a69f9bab8e756c9642] Add a basic jxr reftest for decoding
# good: [765136fe5f1ae2d24bc4c18bb58d36dfe999cb81] Merge pull request #875 from trav90/hunspell-update
git bisect start '203922cfa391a5da64c547a69f9bab8e756c9642' '765136fe5f1ae2d24bc4c18bb58d36dfe999cb81'
# good: [c876894a3baa870f7fc998340f3c2df6beda6c20] Use nsRefPtr in Element::InsertAdjacentTest
git bisect good c876894a3baa870f7fc998340f3c2df6beda6c20
# good: [d2bb5b181903e31c785be31787eec7614fd71185] Add jxrlib files
git bisect good d2bb5b181903e31c785be31787eec7614fd71185
# bad: [a8962ccc722e2a4f7ed21e4b50df93fd75281fae] Add JXR support to the browser
git bisect bad a8962ccc722e2a4f7ed21e4b50df93fd75281fae
# good: [b55f36e7f7a8a6c078bf9ee12003bf238eb087f5] Integrate jxrlib into the build system
git bisect good b55f36e7f7a8a6c078bf9ee12003bf238eb087f5
# first bad commit: [a8962ccc722e2a4f7ed21e4b50df93fd75281fae] Add JXR support to the browser
```
  
The failure: https://gist.github.com/cofi89/0ede1b550c759e01a3a795f7a60cb715  
Config used: https://gist.github.com/cofi89/6a261ed617c21e8fc8a316e13abcf480

System: https://gist.github.com/cofi89/f0e478e0ea6c07ed71f148a2b33cce3c
^ Ignore the unlocked Phenom, it was tortured more than enough and proven to be stable. I get the exact same results from another machine running a Core2Quad 9650. 

Notes:

* `ac_add_options --disable-jxr` doesn't help.
* Manually undoing JXR commits from the current master ( f2179c9d ) = builds and runs fine ( I'm writing this from that build ).
* GCC 5.4 fails the same.
* GCC 4.9 on Jessie also fails at the same point, with a slightly different error, though still the same "lto1: internal compiler error..." ( I managed to reboot without saving the damn log :disappointed:  ). I'll try it again tomorow ( unless it's unnecessary ).
* I haven't tried to build with the BFD linker, nor a non-lto build ( I'm assuming you guys would allready run into issues if there were any ).

If there's any other info/further testing/rebuild needed, let me know.  
Also, many, many thanks to Moonchild and everyone involved for all the effort!!!

Cheers,
Filip

( references #105 & relates to #491 )

**Comment by wolfbeast** [comment] 2017-02-28 08:40
If it's an "internal compiler error" then it is not something we can do to fix; at most we can work around if we know what is going on specifically, or wall paper-disable LTO for the module.
I think this bug report belongs with the gcc people first and foremost. This code clearly tickles it wrong, but no source code should cause a consistent critical failure of a compiler. I think a consistent failure across several versions of the compiler would be helpful to them if it's directly reproducible.

**Comment by rhinoduck** [comment] 2017-03-01 18:03
It is strange that that particular commit should trigger anything when `--disable-jxr` is used. Unless I overlooked something, everything is hidden behind the MOZ_JXR define and, after the preprocessor runs, what the compiler sees should be identical to what it would see as if the commit didn't even exist (minus [one blank line](https://github.com/MoonchildProductions/Pale-Moon/commit/a8962ccc722e2a4f7ed21e4b50df93fd75281fae#diff-df64f800fbd11fea067d30c9c78ffa33R1172) which seems to have slipped in).

There was [this little oversight](https://github.com/MoonchildProductions/Pale-Moon/commit/a8962ccc722e2a4f7ed21e4b50df93fd75281fae#diff-01e1aa9c9dbf602d59e103e42dc83e32R332) on my part which was fixed in https://github.com/MoonchildProductions/Pale-Moon/commit/c88d0cf9e785ef64e6a6c3c2ea5d8c17f7698de7; other than that, with `--disable-jxr`, the JXR code should not enter the picture at all.

**Comment by cofi89** [comment] 2017-03-01 22:31
@wolfbeast, @rhinoduck  

Thank you both for the prompt replies.  

> I think this bug report belongs with the gcc people first and foremost....

Agreed.  
However, it'll have to wait a bit, until I educate my self on how to do it properly ( instead of giving them the ignorant "to reporoduce, clone this and compile it with this config..." style report ).

> It is strange that that particular commit should trigger anything when --disable-jxr is used. Unless I overlooked something, everything is hidden behind the MOZ_JXR define and, after the preprocessor runs, what the compiler sees should be identical to what it would see as if the commit didn't even exist (minus one blank line which seems to have slipped in).
>
> There was this little oversight on my part which was fixed in c88d0cf; other than that, with --disable-jxr, the JXR code should not enter the picture at all.
  
Well, I ran that test ( with `--disable-jxr` ) on the second machine, while bisect session was running on the first, so, besides surelly double-checking the `configure` output to verify that the flag is there, it might still be my bad if I missed/confused something.
I'll try again & log/gist the entire build output.

**Comment by cofi89** [comment] 2017-03-01 23:46
>  I'll try again & log/gist the entire build output.

Nope, fails all the same.
Same [config](https://gist.github.com/cofi89/6a261ed617c21e8fc8a316e13abcf480), latest master.  
Log =  https://gist.github.com/cofi89/3a0d3d3e18657c64f6f0e982f68fffb7

Interesting bit (first occurence at line 1097):
` ... -DMOZ_JXR='1' ...`
So it indeed does gets enabled somehow.


Btw, in case it matters, I originaly forgot to include gcc details:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-8' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170221 (Debian 6.3.0-8)
```

**Comment by wolfbeast** [comment] 2017-03-02 00:46
That's because configure.in is wrong. I just had a look at it.

**Comment by rhinoduck** [comment] 2017-03-02 00:49
I just found the ENABLED/DISABLED mishap as well. It used to be `--enable-jxr` when i started out... my bad. I was about to create a pull request; but perhaps this is easier for you to change yourself than doing the whole dance.

**Comment by cofi89** [comment] 2017-03-02 00:49
After looking around, "MOZ_JXR=1" seemed a bit ouf of place, compared to the rest of the "Enable XYZ" in `configure.in`.  
So I took a shot in the dark and moved it: https://gist.github.com/cofi89/f6058d9d0cd2813303bf96d8b01c4772

`--disable-jxr` is now doing it's job.

**Comment by wolfbeast** [comment] 2017-03-02 00:53
@cofi89 Your gist, although it would work, is a little backwards. My change properly makes it a DISABLE_BOOL and should work while not being inverse logic ;)

**Comment by rhinoduck** [comment] 2017-03-02 01:24
> Nice timing... :smiley:

Indeed. Thanks for bringing this to attention.

**Comment by cofi89** [comment] 2017-03-02 01:38
@wolfbeast 
(now) I see. :smile: 
Btw, aside from a somewhat good knowledge of Bash and some Python, I'm not a programmer. Thus I know almost nothing about AC/M4 specifics, excluding bits thar are/look like the regular `sh`.

Anyway, what matters is that it's now fixed properly, so thank you and @rhinoduck for that, and for looking at it in the first place.  

I'm hopefully gonna have some time this weekend to send a good bug report to GCC guys.

Cheers!

**Comment by wolfbeast** [comment] 2018-04-15 12:45
Any LTO/LTCG issues on UXP will have to be treated separately. Marking this closed as we won't be dealing this on Tycho at this point.

**Closed by wolfbeast** 2018-04-15 12:45 UTC
Labels: Linux, On Hold
