### ISSUE TITLE
Bookmarks importing bugs

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#587] opened 2016-10-11 13:42 UTC
Pale Moon's 'Import Data from Another Browser' feature doesn't sort folders and bookmarks properly (alphabetically, with subfolders on top and bookmarks below.).
Instead, PM sorts the subfolders like bookmarks, scattering them all over the place.

Also, importing large amounts of bookmarks from HTM files will result in PM hanging, and potentialy giving a "Unresponsive script" error message!
## 

Also reported here:
https://forum.palemoon.org/viewtopic.php?f=13&t=12819/
..here:
https://forum.palemoon.org/viewtopic.php?f=29&t=13361/
..and here:
https://forum.palemoon.org/viewtopic.php?f=3&t=16142/

**Comment by mattatobin** [comment] 2016-10-17 07:00
Is this an issue on Tycho?

**Comment by THEtomaso** [comment] 2016-10-17 14:11
Yes.
Check out the second link in my post above.

**Comment by wolfbeast** [comment] 2016-10-17 19:18
How much, exactly, is "large amounts of bookmarks"?

**Comment by THEtomaso** [comment] 2016-10-17 19:38
Like I wrote in the post at the first link above, I've currently got almost 6000.
..but that doesn't really matter, as I've encountered the exact same problem when importing just a few hundred.

**Comment by Lorienna** [comment] 2017-07-29 17:16
<blockquote>importing large amounts of bookmarks from HTM files will result in PM hanging, and potentialy giving a "Unresponsive script" error message</blockquote>

I have a lot of bookmarks too, and so far haven't seen the "Unresponsive script" error on PM, but it shows up on FF quite often, particularly on more recent releases.

However, the HTML importing process takes rather long time indeed, and here's the nightly range for it:

[Last good: `22.0a1 (2013-03-22)`](https://hg.mozilla.org/mozilla-central/rev/0e9badd3cf39) | [First bad: `22.0a1 (2013-03-23)`](https://hg.mozilla.org/mozilla-central/rev/3825fdbcec62) | [Pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=0e9badd3cf39&tochange=3825fdbcec62)
| :-: | :-: | :-: |

@janekptacijarabaci @JustOff  and the Pale Moon team, kindly have a closer look.

**Comment by wolfbeast** [comment] 2017-08-03 06:22
I looked at the pushlog, but nothing stands out as a potential culprit.

**Comment by THEtomaso** [comment] 2017-08-05 01:58
Perhaps as a temporary workaround, the "Unresponsive script" message should be disabled for Pale Moon's Library window.
Also, when importing bookmarks, there could be a message telling users to be patient, as the process can be very slow, and the browser will freeze during the operation.
This would prevent people from using Task Manager to kill palemoon.exe, after assuming that the whole operation has failed.

**Comment by wolfbeast** [comment] 2017-08-05 07:15
It's not possible to special-case the watchdog for script unresponsiveness for just one window, since all Chrome context is the same.

**Comment by THEtomaso** [comment] 2017-08-05 12:13
Well, a simple warning message would be helpful by itself, because there's no way for users to guess that the process actually works, when Pale Moon freezes for several minutes.

**Comment by wolfbeast** [comment] 2017-08-05 12:39
No, what needs to be done is determine what causes this delay, and solve that.

**Comment by THEtomaso** [comment] 2017-08-05 12:51
Yes of course, but like I wrote earlier; this is just a suggestion for a temporary workaround.

**Comment by Lorienna** [comment] 2017-08-06 14:28
@THEtomaso 
How old is your hardware? Is it an aged laptop, perhaps? Are you on Win7? Do you see any errors in the Browser Console?

Would you mind verifying if [FF 22.0a1 (2013-03-22)](https://archive.mozilla.org/pub/firefox/nightly/2013/03/2013-03-22-03-10-28-mozilla-central/) nightly possibly imports your bookmarks without the "Unresponsive script" error and/or faster than [FF 22.0a1 (2013-03-23)](https://archive.mozilla.org/pub/firefox/nightly/2013/03/2013-03-23-03-10-40-mozilla-central/) and Pale Moon? If it doesn't, then you might want to go to [Mozilla Archive](https://archive.mozilla.org/pub/firefox/releases/) and try to find the earliest FF release throwing the "Unresponsive script" error on your system...

**Comment by THEtomaso** [comment] 2017-08-06 15:40
The problem doesn't seem to be hardware related.
I've got Pale Moon istalled on several computers (desktops/laptops/tablets), and under different OS's (Win7/8.1).
The issue occurs on all systems.

Regarding Firefox nightly **v22.0a1 (2013-02-22)** and **v22.0a1 (2013-03-23)**:
It looks like you are wrong in your assumption that these are the last good / first bad releases.
I've tested these builds thoroughly now (with clean profiles), and importing HTM bookmarks works perfectly every time with both of them!
Therefore, the bug must have first appeared in a later FF build.

Pale Moon's Browser Console doesn't show any info when/after importing bookmarks.

When importing bookmarks in PM several times today, I noticed something..
After encountering one of those rare occasions where the process worked flawlessly, I were able to delete all bookmarks and re-import them several times in a row, without running into the bug.
..but as soon as I restarted the browser, the bug took hold again!

**Comment by janekptacijarabaci** [comment] 2017-08-06 16:33
I'm trying to import >5000 (i.e. >10000) bookmarks (repeatedly)... Without "success".
AFAIK: The "last good" and "first bad" range will be needed.

**Comment by wolfbeast** [comment] 2017-08-06 16:42
If it's intermittent, then perhaps the problem is in the realm of the import being spawned as an asynchronous process. Perhaps making it synchronous will resolve the issue in that case; either way, getting a regression range will help tremendously.

**Comment by THEtomaso** [comment] 2017-08-06 16:56
> I'm trying to import >5000 (i.e. >10000) bookmarks (repeatedly)... Without "success".

Read previous posts.
Importing bookmarks DOES work, but it takes a long time.
You need to be patient and wait several minutes.
Pale Moon will freeze during the operation, but will automatically recover itself when the process have completed.
For me, this takes approximately 5 minutes.

**Comment by janekptacijarabaci** [comment] 2017-08-06 17:15
"success" = it works without any problem :-)

For me, this takes approximately <30 seconds.

**Comment by THEtomaso** [comment] 2017-08-06 17:22
> For me, this takes approximately <30 seconds.

You got lucky and encountered one of those exceptions that I've also mentioned before.
Sometimes, the process works like expected, and only takes a few seconds.
You will then be able to delete and re-import bookmarks repeatedly, without any issues, until the browser is restarted.

**Comment by janekptacijarabaci** [comment] 2017-08-06 17:30
I've also tried to reboot several times...

**Comment by THEtomaso** [comment] 2017-08-06 18:10
> I'm trying to import >5000 (i.e. >10000) bookmarks (repeatedly)... Without "success".
AFAIK: The "last good" and "first bad" range will be needed.

> Without "success" = it works without any problem :-)

Your statements are contradicting to me.
Are you saying that importing bookmarks works without any issues for you, and it only takes a few seconmds every time?
Even after restarting the browser?

**Comment by janekptacijarabaci** [comment] 2017-08-06 18:23
Yes. Something is different and/or we have different bookmarks (e.g. a special bookmark with "special url").
I don't know...

**Comment by THEtomaso** [comment] 2017-08-06 18:55
Or perhaps you aren't even importing from HTM files?

**Comment by janekptacijarabaci** [comment] 2017-08-06 19:06
No, I import.

**Comment by Lorienna** [comment] 2017-08-07 01:50
@THEtomaso 

Please download and thoroughly verify [FF 30.0](https://archive.mozilla.org/pub/firefox/releases/30.0/). If it's bad, then kindly begin _bi-secting_ the releases (in your mind) by downloading and testing [FF 26.0](https://archive.mozilla.org/pub/firefox/releases/26.0/) first, then what's in the middle of those two (should FF 26.0 be good), down until [FF 22.0](https://archive.mozilla.org/pub/firefox/releases/22.0/), if needed.

But if FF 30.0 imports your bookmarks fine, then please repeat the same with [FF 34.0](https://archive.mozilla.org/pub/firefox/releases/34.0/), [FF 38.0](https://archive.mozilla.org/pub/firefox/releases/38.0/) and so on...

After you accomplish this, please report the first affected release here, and hopefully the gentlemen here will kindly instruct you how to use [MozRegression tool](https://github.com/mozilla/mozregression/releases) to find the regression range :)

**Comment by THEtomaso** [comment] 2017-08-08 10:14
I think the problem might first have started somewhere between FF's v22.0 and v23.0 release.
Also, it seems to me that it's somehow related to how you've configured your history settings.
When trying to confirm this, I stumbled across another bug:
https://github.com/MoonchildProductions/Pale-Moon/issues/1282/

**Comment by THEtomaso** [comment] 2017-08-08 14:09
There's a long discussion regarding the issue here:
https://support.mozilla.org/questions/1100618/
Some workarounds are mentioned, which has to do with the **places.sqlite** file, but no real fix per se.
Perhaps someone here can get something useful out of this info?

**Comment by Lorienna** [comment] 2017-08-08 23:09
@THEtomaso 
Thank you for verifying. Please also download, test and report which of the following builds are affected:

1. The last FF 22 aurora: [22.0a2 (2013-05-13)](https://archive.mozilla.org/pub/firefox/nightly/2013/05/2013-05-13-00-40-17-mozilla-aurora/);
2. The first FF 23 nightly: [23.0a1 (2013-04-02)](https://archive.mozilla.org/pub/firefox/nightly/2013/04/2013-04-02-03-08-43-mozilla-central/);
3. The last FF 23 nightly: [23.0a1 (2013-05-13)](https://archive.mozilla.org/pub/firefox/nightly/2013/05/2013-05-13-03-10-57-mozilla-central/);
4. The current latest nightly: [57.0a1 (2017-08-08)](https://archive.mozilla.org/pub/firefox/nightly/2017/08/2017-08-08-11-40-32-mozilla-central/).

**Comment by wolfbeast** [comment] 2017-08-09 00:25
@Lorienna You're acting like you plan to work on this and want to be assigned. Is that correct? If not, why are you putting on a developer's cap, asking for manual testing of Firefox versions?

**Comment by THEtomaso** [comment] 2017-08-09 14:12
This issue is somewhat difficult to troubleshoot, as it doesn't occur consistently.
..but my tests now indicate that the issue first seems to have appeared between Firefox **v23.0a1 (2013-05-13)** and **v23.0 Final**.

However, it should also be noted that Firefox versions prior to v23.0 is not completely trouble free in this regard either, as they suffer from a slightly different problem..
None of them appears to have any problem with IMPORTING bookmarks, but instead they throw a "Unresponsive script" error when DELETING them!
Pale Moon currently does not suffer from this issue.

As for Firefox **v57.0a1**; that's a different beast entirely..
Indeed, Mozilla have obviously made some changes to how they handle bookmarks in this version, but instead of properly fixing the issue at hand, they appear to have implemented some sort of a sloppy workaround..
When the process of importing bookmarks appears to have completed, it still isn't entirely done.
..and during the painfully slow process of deleting bookmarks, you can observe every bookmark/folder being removed one by one.
Also, when the processes have completed, the browser still hangs for a short while.

**Comment by Lorienna** [comment] 2017-11-01 11:30
I'm sorry if my asking to test the builds caused anyone trouble here.

<blockquote>If it's intermittent, then perhaps the problem is in the realm of the import being spawned as an asynchronous process. Perhaps making it synchronous will resolve the issue in that case</blockquote>

Was it probably FF 14 where the asynchronous HTML import was first implemented, introducing the [BookmarkHTMLUtils.jsm](https://hg.mozilla.org/mozilla-central/diff/404738948156/toolkit/components/places/BookmarkHTMLUtils.jsm) module, among other things?

###### < [14.0a1 (2012-03-24)](https://hg.mozilla.org/mozilla-central/rev/df1f94b2bdee) > [Pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=df1f94b2bdee&tochange=20a01901480f) </ [14.0a1 (2012-03-25)](https://hg.mozilla.org/mozilla-central/rev/20a01901480f) ><br><br>< [Bug 482911](https://bugzilla.mozilla.org/show_bug.cgi?id=482911) > [HTML5] Re-implement bookmarks.html parsing using the HTML5 parser. </ ><br>< [Changeset 90153](https://hg.mozilla.org/mozilla-central/rev/404738948156) > Reimplement Netscape bookmark import using the HTML5 parser. </ ><br>< [Changeset 90154](https://hg.mozilla.org/mozilla-central/rev/adc7f3ed2d78) > addendum - Tell nsBrowserGlue not to import initial bookmarks in a couple of tests to avoid fatal assertions on Mac. </ >

**Comment by Lorienna** [comment] 2017-11-04 10:30
<blockquote>'Import Data from Another Browser' feature doesn't sort folders and bookmarks properly (alphabetically, with subfolders on top and bookmarks below.).</blockquote>

[Bug 248352](https://bugzilla.mozilla.org/show_bug.cgi?id=248352) - <q>Preserve sort order when migrating bookmarks from IE</q>.

**Comment by wolfbeast** [comment] 2018-06-05 14:11
We'll be removing the internal browser migration wizard in UXP. It's unmaintainable. Closing this issue without cloning it.

**Closed by wolfbeast** 2018-06-05 14:11 UTC
