### ISSUE TITLE
JPEG - Double extension bug

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1673] opened 2018-05-19 12:13 UTC
**Description**:
When saving JPEG files in Pale Moon, they end up with a double extension, like this:
somefilename.JPEG.JPG

**Example**:
`https://assets.ynap-content.com/story-metadata-image-1520511428432.jpeg`

**How to reproduce:**
Save the image in my example above.
The file will end up like this:
`story-metadata-image-1520511428432.jpeg.jpg`

--

OS: Win8.1Pro,x64
PM: 27.9.2,x64

**Comment by JustOff** [comment] 2018-05-19 12:18
I can't reproduce this.

**Comment by THEtomaso** [comment] 2018-05-19 12:28
The same issue occurs with Basilisk and SeaMonkey.
But K-Meleon v75.1 saves the files correctly.

**Comment by JustOff** [comment] 2018-05-19 12:32
Firefox? Chrome? 

Although I think that in any case there is nothing to fix here.

**Comment by THEtomaso** [comment] 2018-05-19 12:41
I just installed the latest version of SRWare Iron, and gave it a try..
No such issue there.

**Comment by THEtomaso** [comment] 2018-05-19 12:56
Thought it might be a configuration thing..
But the issue also occurs with a Pale Moon Portable, freshly unpacked, and all settings at default.

**Comment by wolfbeast** [comment] 2018-05-19 13:13
Check your system configuration. Is "jpeg" as an extension associated with anything in your O.S.? or just "jpg"?

**Comment by wolfbeast** [comment] 2018-05-19 13:26
Not a browser bug - closing

**Closed by wolfbeast** 2018-05-19 13:26 UTC
