### ISSUE TITLE
GitHub site display breaks when scrolling

### ISSUE THREAD

**Issue by Gpower2** [MoonchildProductions/Pale-Moon#1525] opened 2017-12-02 09:30 UTC
I noticed a strange bug, possibly related to #1496 , where Github display breaks when scrolling.
Notice the break here:
![bad](https://user-images.githubusercontent.com/2773398/33513966-19512b3c-d754-11e7-8be4-ae97744ac51c.png)
If you scroll at another offset, everything looks good!
![good](https://user-images.githubusercontent.com/2773398/33513968-1df709b8-d754-11e7-88c4-3b07b7d0cf49.png)

**Comment by wolfbeast** [comment] 2017-12-02 10:16
I can indeed reproduce this -- looks like some rounding error/pixel-snapping error (unrelated to the actual issue linked to) that puts the svg parts of the button snapped one pixel lower than the rest.

**Comment by Gpower2** [comment] 2017-12-02 10:28
Notice that it's not only the buttons that are affected, but the grid lines also.

**Comment by janekptacijarabaci** [comment] 2017-12-02 12:30
Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=6608e5864780589b25d5421c3d3673ab30c4c318&tochange=1576e7bc1bec7232e9e4ba78cce62526b1a6380b

**Comment by wolfbeast** [comment] 2017-12-02 13:07
Nothing in that pushlog stands out as an obvious culprit :(

**Comment by wolfbeast** [comment] 2017-12-02 13:22
It seems to be purely a rendering error. Switching tabs fixes the offset, which doesn't do new layout.

**Comment by Gpower2** [comment] 2018-01-20 12:12
With PaleMoon v27.7.1 this problems seems solved!
Perhaps solving issue #1556 also solved this? *shrugs*

**Comment by mattatobin** [comment] 2018-01-20 14:44
Or GitHub solved it on their side.

**Comment by wolfbeast** [comment] 2018-01-20 19:45
Confirmed solved - closing.

**Closed by wolfbeast** 2018-01-20 19:45 UTC
Labels: Rendering
