### ISSUE TITLE
Hangs on Facebook (and possibly others)

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#920] opened 2017-02-25 23:04 UTC
From what I can gather from the hang reports submitted by different people, we're still seeing hangs in the mediadecoder, specifically `MediaDecoder::NotifyOwnerActivityChanged()`, where it will hang on a re-entrant guard `ReentrantMonitorAutoEnter mon(GetReentrantMonitor());`

The fact that this guard calls into nss threw me off but I've traced back the first usable xul.dll address to this particular function.

Perhaps this is running on a different thread than the main thread, which would likely assert in a debug build, but in a release build just hangs.
Because it is a hang, the call stack doesn't help much but I'll see if I can dig a bit deeper.

**Comment by wolfbeast** [comment] 2017-02-25 23:05
@trav90 -- do you have any idea off-hand what might be a cause?

**Comment by wolfbeast** [comment] 2017-02-25 23:16
As far as I can gather from the latest hang report's addresses, the call stack is as follows:
`MediaDecoder::NotifyOwnerActivityChanged()` -> `ReentrantMonitorAutoEnter mon(GetReentrantMonitor());`
called from
`mozilla::dom::HTMLMediaElement::NotifyOwnerDocumentActivityChanged(void)` -> `if (UseAudioChannelService() && mPlayingThroughTheAudioChannel &&
      mAudioChannelAgent)`
called from
`NS_INTERFACE_MAP_END_INHERITING(nsGenericHTMLElement)` -> `nsGenericHTMLElement::QueryInterface` which is part of a Cycle Collection block.
(HTMLMediaElement.cpp L475-480)

So we may have a problem that it got cycle collected, and then trying to use the dead/recycled object...

**Comment by trav90** [comment] 2017-02-26 06:35
> do you have any idea off-hand what might be a cause?

Not off-hand, but I'll dig into this and see if I can come up with a cause.

**Comment by wolfbeast** [comment] 2017-02-26 07:36
From what I can see, the ReentrantMonitor in MediaDecoder is used to protect playback statistics (at least that's what the header says) -- http://xref.palemoon.org/palemoon-trunk/source/dom/media/MediaDecoder.h#991 maybe that helps finding the cause?

**Comment by wolfbeast** [comment] 2017-02-26 08:07
`MediaDecoder::NotifyOwnerActivityChanged()` seems rather fragile. Why don't we just check there if the decoder has been shut down instead of using a reentrant monitor?

e.g. do a similar check as in `MediaDecoder::UpdateDormantState` and at the very least return if `mPlayState == PLAY_STATE_SHUTDOWN` or you don't have a MDSM?
I'm not familiar with the code you've been poking at but it seems a reasonable alternative off-hand.

**Comment by wolfbeast** [comment] 2017-02-27 10:06
With the help of Tobin who can reproduce this hang and plugging into the debugger, it seems the callstack I indicated was wrong. Instead it traces back to the following:

````C++
MediaDecoderOwner::NextFrameStatus MediaDecoderStateMachine::GetNextFrameStatus()
{
  ReentrantMonitorAutoEnter mon(mDecoder->GetReentrantMonitor());
  if (IsBuffering()) {
    return MediaDecoderOwner::NEXT_FRAME_UNAVAILABLE_BUFFERING;
  } else if (IsSeeking()) {
    return MediaDecoderOwner::NEXT_FRAME_UNAVAILABLE_SEEKING;
  } else if (HaveNextFrameData()) {
    return MediaDecoderOwner::NEXT_FRAME_AVAILABLE;
  }
  return MediaDecoderOwner::NEXT_FRAME_UNAVAILABLE;
}
````
It hangs on `ReentrantMonitorAutoEnter mon(mDecoder->GetReentrantMonitor());`

this is called from:
````C++
void MediaDecoder::UpdateReadyStateForData()
{
  MOZ_ASSERT(NS_IsMainThread());
  if (!mOwner || mShuttingDown || !mDecoderStateMachine) {
    return;
  }
  MediaDecoderOwner::NextFrameStatus frameStatus =
    mDecoderStateMachine->GetNextFrameStatus();
  mOwner->UpdateReadyStateForData(frameStatus);
}
````
caller: `mDecoderStateMachine->GetNextFrameStatus();`

full stack:
````
 	nss3.dll!_PR_MD_WAIT_CV(_MDCVar * cv, _MDLock * lock, unsigned int timeout) Line 250	C
 	nss3.dll!_PR_WaitCondVar(PRThread * thread, PRCondVar * cvar, PRLock * lock, unsigned int timeout) Line 172	C
 	nss3.dll!PR_WaitCondVar(PRCondVar * cvar, unsigned int timeout) Line 525	C
 	nss3.dll!PR_EnterMonitor(PRMonitor * mon) Line 136	C
 	xul.dll!mozilla::MediaDecoderStateMachine::GetNextFrameStatus() Line 1310	C++
>	xul.dll!mozilla::MediaDecoder::UpdateReadyStateForData() Line 1221	C++
 	xul.dll!nsRunnableMethodImpl<void (__thiscall mozilla::net::HttpChannelParent::*)(void),1>::Run() Line 682	C++
 	xul.dll!nsThread::ProcessNextEvent(bool aMayWait, bool * aResult) Line 807	C++
````

So I think it must be some case of either the wrong thread or mDecoder (most likely) or maybe mDecoderStateachine having been GCed or CCed or otherwise discarded if it was a weak ref. maybe you can figure out from the different bugs what's going on, @trav90

**Comment by trav90** [comment] 2017-02-27 10:12
That callstack does make a little more sense. I'm looking into it.

**Comment by wolfbeast** [comment] 2017-02-27 10:19
Looks like we did lose mDecoder (checking locals). The calling site checks on the others but not if we still have a decoder.

**Comment by wolfbeast** [comment] 2017-02-27 11:25
And the previous hang is still present, with the following stack:
````
 	nss3.dll!_PR_MD_WAIT_CV(_MDCVar * cv, _MDLock * lock, unsigned int timeout) Line 250	C
 	nss3.dll!_PR_WaitCondVar(PRThread * thread, PRCondVar * cvar, PRLock * lock, unsigned int timeout) Line 172	C
 	nss3.dll!PR_WaitCondVar(PRCondVar * cvar, unsigned int timeout) Line 525	C
 	nss3.dll!PR_EnterMonitor(PRMonitor * mon) Line 136	C
 	xul.dll!mozilla::MediaDecoder::NotifyOwnerActivityChanged() Line 126	C++
>	xul.dll!mozilla::dom::HTMLMediaElement::NotifyOwnerDocumentActivityChanged() Line 3920	C++
 	xul.dll!mozilla::dom::HTMLVideoElement::NotifyOwnerDocumentActivityChanged() Line 195	C++
 	xul.dll!NotifyActivityChanged(nsISupports * aSupports, void * aUnused) Line 4591	C++
````

**Comment by trav90** [comment] 2017-03-01 06:47
I have a potential lead - the hang doesn't appear to happen when the MediaFormatReader is disabled. I've [ported a patch](https://github.com/trav90/Pale-Moon/commit/1c380db042959225296174cb39c336b79c653d35) from Mozilla that resolves a potential deadlock with the decoder monitor in the MFR.

Tobin is currently testing this patch to see if the hang is still reproducible.

If this works, while not a solution to the root problem, it should be something we can push out in a point release for all those affected by this bug.

**Comment by wolfbeast** [comment] 2017-03-02 01:28
I'm going to just pull your patch across to the relbranch, and make a point release out of it. I need to add Yandex as a search engine soon anyway so may as well bundle that together.

**Comment by Sa-Ja-Di** [comment] 2017-03-05 11:38
The latest unstable also has now again improved Twitch playback with MSE-MP4 as it seems. Can switch with activated "media.mediasource.format-reader.mp4" between Twitch quality steps without the video suddenly looping or stopping in playback.

So, the hangs reported for Facebook and others are also related with Twitch video playback problems.

Testing now a couple of streams and so far stuff also in that section has improved as it looks like. So, a part of #908 at least is related to this bug too.

Good work so far from you guys :) :+1:

**Comment by mattatobin** [comment] 2017-03-08 16:57
@trav90 remember that hard to reproduce almost never but sometimes hang we didn't mention? Well.. It has happened enough but not reliaby and not always that I think it should be mentioned.

Stack Trace.. Of course your latest PR may help it.. but regardless..
```
 	nss3.dll!_PR_MD_WAIT_CV(_MDCVar * cv, _MDLock * lock, unsigned int timeout) Line 250	C
 	nss3.dll!_PR_WaitCondVar(PRThread * thread, PRCondVar * cvar, PRLock * lock, unsigned int timeout) Line 172	C
 	nss3.dll!PR_WaitCondVar(PRCondVar * cvar, unsigned int timeout) Line 525	C
 	nss3.dll!PR_EnterMonitor(PRMonitor * mon) Line 136	C
 	xul.dll!mozilla::MediaDecoderStateMachine::GetBuffered() Line 304	C++
 	xul.dll!mozilla::MediaDecoder::GetBuffered() Line 1627	C++
	xul.dll!mozilla::dom::HTMLMediaElement::Buffered() Line 4132	C++
 	xul.dll!mozilla::dom::HTMLMediaElementBinding::get_buffered(JSContext * cx, JS::Handle<JSObject *> obj, mozilla::dom::HTMLMediaElement * self, JSJitGetterCallArgs args) Line 304	C++
 	xul.dll!mozilla::dom::GenericBindingGetter(JSContext * cx, unsigned int argc, JS::Value * vp) Line 2467	C++
 	mozjs.dll!js::jit::DoCallNativeGetter(JSContext * cx, JS::Handle<JSFunction *> callee, JS::Handle<JSObject *> obj, JS::MutableHandle<JS::Value> result) Line 1584	C++
```

**Comment by trav90** [comment] 2017-03-09 07:59
Thanks @mattatobin. haven't forgotten about this; still investigating.

**Comment by trav90** [comment] 2017-04-23 10:28
The original hang/deadlock reported in this issue has been fixed. Has anyone experienced or able to reproduce the second hang mentioned here?

**Comment by wolfbeast** [comment] 2017-04-23 10:28
What's the status on this? still 27.3 or tied in with the MSE improvements for 27.4?

**Comment by wolfbeast** [comment] 2017-04-23 10:30
Hah, we mid-aired here. If the original deadlock in this one has been solved, then we should consider the second hang a separate issue if it can still be reproduced.

**Comment by trav90** [comment] 2017-04-23 10:35
Yup sure did. Agreed. Considering this issue solved and closing. If the second hang is still reproducible, please open a new issue for it.

**Closed by trav90** 2017-04-23 10:35 UTC
Labels: Bug, Media
