### ISSUE TITLE
Vidoes don't play on some sites if MSE is enabled

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1334] opened 2017-09-07 17:36 UTC
Videos in articles @ NRK.no can't be played with MSE enabled.

Here's an example:
https://www.nrk.no/urix/slik-ser-_irma_-ut-fra-verdensrommet-1.13677733

Tested with Pale Moon v27.4.2,x64 and v27.5.0a1,x86 (2017-09-07)

**Comment by trav90** [comment] 2017-09-14 07:15
I have an idea that if successful, will provide a (temporary) workaround for these sorts of issues. As I am a bit short on time at the moment, could someone (possibly @THEtomaso?) scour the forum (as I know there have been more reports there) and post a list of additional domains (in addition to nrk.co) where videos do not play unless MSE is disabled?

**Comment by THEtomaso** [comment] 2017-09-14 11:04
Here are some that I found:
https://forum.palemoon.org/viewtopic.php?f=3&t=16229/
https://forum.palemoon.org/viewtopic.php?f=3&t=16597/
https://forum.palemoon.org/viewtopic.php?f=3&t=16668/
https://forum.palemoon.org/viewtopic.php?f=29&t=16262/

**Comment by trav90** [comment] 2017-09-15 04:54
Thank you!

**Comment by THEtomaso** [comment] 2017-09-24 14:53
With MSE enabled, some videos will suddenly just stop @ VGTV.no.
Toggling the fullscreen windows seems to trigger it sometimes.

Longer videos won't play at all (regardless of the MSE settings), like this one:
http://www.vgtv.no/video/146986

**Comment by adeshkp** [comment] 2017-09-26 09:13
@THEtomaso The video you linked says that it can only be played from Norway. So I tried another longer video - http://www.vgtv.no/video/142542/mystery-at-the-oslo-plaza (30 min) plays without any issues using default video settings.
Using ver 27.4.2 32-bit on Linux.

**Comment by wolfbeast** [comment] 2017-09-26 09:30
I can confirm that the video @adeshkp linked to plays just fine in 27.4.2 x86 on Windows as well.

**Comment by THEtomaso** [comment] 2017-09-26 18:42
Regarding the video that adeshkp linked to:
Try maximizing the window..
This soon causes the video to start buffering.
But if you disable MSE, it works just fine.

**Comment by THEtomaso** [comment] 2017-10-09 19:01
Here's how to reproduce the issue with short videos:

1) Make sure that MSE is enabled.

2) Go to this page:
https://www.vgtv.no/video/145910

3) As soon as the video starts playing, click on the player's fullscreen button.

4) The video will start buffering after about 8 seconds.

**Comment by adeshkp** [comment] 2017-10-10 09:25
Tried that, was able to play full video. Trying it multiple times, I noticed that I too get buffering circle a few times, but it goes away soon and the video continues. So, this might be dependent on internet connection speed.

But I must say the playback was smooth in normal mode. In fullscreen mode, to me it looks like, the site is switching between standard and HD quality, and thats when the buffering starts.

**Comment by wolfbeast** [comment] 2017-10-10 10:20
VGTV.no: going by adesh's description, this sounds to me like it's a server-side bandwidth issue. It tries to use DASH to compensate by switching between different resolution streams, but if the server is overloaded, then you may have BW-switched buffering requests being dropped on the floor. Without MSE, DASH is not an option and the server will not reconnect/re-buffer, but rather just "send data as best as it can" so you won't get the loading throbber in that case.

That isn't anything the browser can "fix" and isn't a bug.

Are there any other actionable issues here?

**Comment by THEtomaso** [comment] 2017-10-10 13:59
I've got no such problem in SeaMonkey.

My connection:
Speed = 300 / 300 Mbps
Ping (www.vgtv.no) = 20 ms

**Comment by janekptacijarabaci** [comment] 2017-10-10 15:30
Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=cfc7ebe592937ad937cebe04fdad4213eee72fae&tochange=9ce31e9f90cb0e534611b0f617c5bbc232ffe748

After this patch:
https://bugzilla.mozilla.org/show_bug.cgi?id=1247138
it doesn't make any error, but stream does not work properly (the playback stops), see also (?):
https://bugzilla.mozilla.org/show_bug.cgi?id=1264199

**Comment by THEtomaso** [comment] 2017-10-10 16:27
Yes, I can confirm that VGTV's videos plays just fine in Pale Moon v27.3.0, with MSE enabled (both the short ones and the long ones)!
Thanks for taking your time to troubleshoot this issue.

**Comment by trav90** [comment] 2017-10-11 05:01
> After this patch:
https://bugzilla.mozilla.org/show_bug.cgi?id=1247138
it doesn't make any error, but stream does not work properly

Because our backedend does not have what is required to support audio configuration change using our async MSE code.

It works in Pale Moon 27.3 because our new async MSE was not enabled by default until 27.4.0.

**Comment by wolfbeast** [comment] 2018-04-15 12:54
UXP should solve these media woes once and for all. Closing.

**Closed by wolfbeast** 2018-04-15 12:54 UTC
Labels: Media - MSE, Solved by UXP
