### ISSUE TITLE
Debug build fails -- "subproperty must be a longhand"

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/Pale-Moon#344] opened 2016-02-02 08:36 UTC
On Mac clang, building with `--enable-debug` fails:

```
108:33.36 libbrowsercomps.dylib
108:35.77 nsBrowserApp.cpp
108:47.14 /Users/pale/jenkins/workspace/palemoon/config/rules.mk:1239: warning: overriding commands for target `Makefile'
108:47.14 /Users/pale/jenkins/workspace/palemoon/config/rules.mk:631: warning: ignoring old commands for target `Makefile'
108:48.23 /Users/pale/jenkins/workspace/palemoon/config/rules.mk:1239: warning: overriding commands for target `Makefile'
108:48.23 /Users/pale/jenkins/workspace/palemoon/config/rules.mk:631: warning: ignoring old commands for target `Makefile'
108:57.07 Executing /Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/bin/xpcshell -g /Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS -a /Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS -f /Users/pale/jenkins/workspace/palemoon/toolkit/mozapps/installer/precompile_cache.js -e precompile_startupcache("resource://gre/");
109:01.51 WARNING: XPCOM objects created/destroyed from static ctor/dtor: file /Users/pale/jenkins/workspace/palemoon/xpcom/base/nsTraceRefcntImpl.cpp, line 141
109:01.89 ###!!! ABORT: subproperty must be a longhand: '0 < *subprops && *subprops < eCSSProperty_COUNT_no_shorthands', file /Users/pale/jenkins/workspace/palemoon/layout/style/nsCSSProps.cpp, line 200
109:02.02 nsCSSProps::BuildShorthandsContainingTable()+0x0000012A [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x007E15FA]
109:02.02 nsCSSProps::AddRefTable()+0x000003E6 [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x007E0A06]
109:02.03 nsLayoutStatics::Initialize()+0x0000008B [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x0049223B]
109:02.03 Initialize()+0x00000093 [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x004899F3]
109:02.04 nsComponentManagerImpl::KnownModule::Load()+0x000000DD [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02DFE91D]
109:02.05 nsFactoryEntry::GetFactory()+0x00000084 [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02DFF454]
109:02.06 nsComponentManagerImpl::CreateInstanceByContractID(char const*, nsISupports*, nsID const&, void**)+0x0000010F [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02DFFECF]
109:02.06 nsComponentManagerImpl::GetServiceByContractID(char const*, nsID const&, void**)+0x0000047E [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02DFB9BE]
109:02.07 CallGetService(char const*, nsID const&, void**)+0x00000095 [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02D69405]
109:02.08 nsGetServiceByContractID::operator()(nsID const&, void**) const+0x00000028 [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02D69B38]
109:02.08 nsCOMPtr_base::assign_from_gs_contractid(nsGetServiceByContractID, nsID const&)+0x00000033 [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02D67033]
109:02.09 nsCOMPtr<nsISupports>::nsCOMPtr(nsGetServiceByContractID)+0x0000004C [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02D80A7C]
109:02.09 nsCOMPtr<nsISupports>::nsCOMPtr(nsGetServiceByContractID)+0x0000001D [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02D8049D]
109:02.11 NS_InitXPCOM2+0x00000CBE [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/NewMoonDebug.app/Contents/MacOS/XUL +0x02D7D17E]
109:02.11 main+0x000007EC [/Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/bin/xpcshell +0x00001F9C]
109:02.11 ###!!! ABORT: subproperty must be a longhand: '0 < *subprops && *subprops < eCSSProperty_COUNT_no_shorthands', file /Users/pale/jenkins/workspace/palemoon/layout/style/nsCSSProps.cpp, line 200
111:29.80 Traceback (most recent call last):
111:29.80   File "/Users/pale/jenkins/workspace/palemoon/toolkit/mozapps/installer/packager.py", line 376, in <module>
111:29.81     main()
111:29.81   File "/Users/pale/jenkins/workspace/palemoon/toolkit/mozapps/installer/packager.py", line 368, in main
111:29.81     args.source, gre_path, base)
111:29.82   File "/Users/pale/jenkins/workspace/palemoon/toolkit/mozapps/installer/packager.py", line 148, in precompile_cache
111:29.82     errors.fatal('Error while running startup cache precompilation')
111:29.82   File "/Users/pale/jenkins/workspace/palemoon/python/mozbuild/mozpack/errors.py", line 101, in fatal
111:29.82     self._handle(self.FATAL, msg)
111:29.83   File "/Users/pale/jenkins/workspace/palemoon/python/mozbuild/mozpack/errors.py", line 96, in _handle
111:29.83     raise ErrorMessage(msg)
111:29.83 mozpack.errors.ErrorMessage: Error: Error while running startup cache precompilation
111:29.87 make[3]: *** [stage-package] Error 1
111:29.87 make[2]: *** [postflight_all] Error 2
111:29.88 make[1]: *** [realbuild] Error 2
111:29.88 make: *** [build] Error 2
```

Is the debug build used at all?  I'm not sure if this is a Mac-specific error or not.

**Comment by wolfbeast** [comment] 2016-02-02 13:14
It fails on precompiling the startup cache. This is a common error -- but didn't we work around that already?
Unfortunately the error doesn't specify WHICH CSS property it trips over, which isn't very helpful. Thanks, Mozilla.

**Comment by Axiomatic-** [comment] 2016-02-21 04:03
I hit this on Linux as well, using `git blame` in gecko-dev pops up [bug 921797](https://bugzilla.mozilla.org/show_bug.cgi?id=921797), patch below: 

```patch
diff --git a/layout/style/nsCSSProps.cpp b/layout/style/nsCSSProps.cpp
index aa10e7c..3ddeaae 100644
--- a/layout/style/nsCSSProps.cpp
+++ b/layout/style/nsCSSProps.cpp
@@ -195,7 +195,7 @@ nsCSSProps::BuildShorthandsContainingTable()
     for (const nsCSSProperty* subprops = SubpropertyEntryFor(shorthand);
          *subprops != eCSSProperty_UNKNOWN;
          ++subprops) {
-      NS_ABORT_IF_FALSE(0 < *subprops &&
+      NS_ABORT_IF_FALSE(0 <= *subprops &&
                         *subprops < eCSSProperty_COUNT_no_shorthands,
                         "subproperty must be a longhand");
       ++occurrenceCounts[*subprops];
```

It should be able to be cherry picked over with metadata; @stevenschlansker or @wolfbeast want to do this? (I cannot because of living in the boondocks with slow internet, sorry.)

**Comment by wolfbeast** [comment] 2016-02-21 09:20
Patch applied to tip of master. Please test?

**Comment by Axiomatic-** [comment] 2016-02-21 09:24
Already have, I can confirm the debug build, builds on Linux now.

**Comment by wolfbeast** [comment] 2016-02-21 11:41
Awesome! Closing.

**Closed by wolfbeast** 2016-02-21 11:41 UTC
