### ISSUE TITLE
github code signature broken on some pages and cannot download

### ISSUE THREAD

**Issue by RoyBatty64** [MoonchildProductions/Pale-Moon#1764] opened 2020-04-06 21:01 UTC
I had opened an issue with this before, but the bug was not a problem until it occurred again lately.

This happens regularly on github and I have to use another browser to download, finally got a link with multiple failures on the same page.

https://github.com/saramibreak/DiscImageCreator/releases

Attempting to download any of the zips results in this error.

**Comment by SpockFan02** [comment] 2020-04-06 21:27
I tried the first two (DiscImageCreator_20200403.zip and DiscImageCreator_20200204.zip) and was able to download both just fine using Pale Moon 29.0.0a3 on macOS.

**Comment by wolfbeast** [comment] 2020-04-07 12:21
What exactly do you mean with "code signature broken"? Downloads are fine here as well, using latest release version of Pale Moon.

**Comment by RoyBatty64** [comment] 2020-04-12 00:55
I mean this

https://i.imgur.com/lsxMUw9.png

This happens regularly with PaleMoon and no other browser. On Windows 7 Enterprise X64.

**Comment by wolfbeast** [comment] 2020-04-12 15:57
That's a server-side error (that I haven't seen before) indicating a checksum mismatch (by the looks of it between origin server and CDN). Nothing the browser can do anything about.

**Comment by RoyBatty64** [comment] 2020-04-12 21:44
Why does it work flawlessly in every other browser then? Something is up with that.

**Comment by wolfbeast** [comment] 2020-04-12 23:28
Why does it work flawlessly for anyone but you in Pale Moon? Something is up with that too.
If it was a browser problem, others would also experience the same. Have you actually tried every other browser? Or just Edge and Chrome? Are those other browsers actually connecting to the same edge server or not?

**Comment by wolfbeast** [comment] 2020-04-16 11:29
Unable to reproduce, closing as WFM

**Closed by wolfbeast** 2020-04-16 11:29 UTC
Labels: Works For Me
