### ISSUE TITLE
Chat on YouTube livestream no longer working

### ISSUE THREAD

**Issue by xbeyond1** [MoonchildProductions/Pale-Moon#827] opened 2017-01-13 08:23 UTC
Seems that the chatroom feature doesn't work with PM anymore, since YouTube thinks the browser is outdated. 

![youtubechat](https://cloud.githubusercontent.com/assets/22633092/21923000/5052adf0-d97a-11e6-8d92-887cad819487.png)

**Comment by janekptacijarabaci** [comment] 2017-01-13 08:35
Dupe of https://github.com/MoonchildProductions/Pale-Moon/issues/816

**Closed** 2017-01-13 10:41 UTC
Labels: Duplicate
