### ISSUE TITLE
Text input gets stuck on one window

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#66] opened 2015-05-02 00:12 UTC
Haven't quite fully narrowed down the cause yet but seems like when I create a new window by right-clicking a link -> new window, and create a new tab within it  by control-left click... that I'm no longer able to type in the first window (text gets added to whatever most recent text field in the old window I was typing in).  Right now, for example, I have twitter on one window, and I click on the text field, it *highlights* as if it's plain text but it does not drop the cursor in.

palemoon 8a7cc2e 
gcc 4.9.2
ubuntu 15.04

**Comment by trav90** [comment] 2015-05-02 01:24
Unable to reproduce with 25.4.0b3 on Manjaro

**Comment by Axiomatic-** [comment] 2015-05-02 03:25
Same as Trav, I am unable to reproduce the issue you described. It sounds like some iffy desktop manager, or window manager issue though (misdirected focus maybe?). If you are using Unity try GNOME, or vies-versa.

**Comment by themusicgod1** [comment] 2015-05-03 04:56
Will try to reproduce, I was using ubuntu-gnome-desktop (0.38) if that helps

**Comment by chaoskagami** [comment] 2015-06-11 18:18
I can't reproduce this. I'm running LFS with a awesome/MATE desktop combination.

**Comment by themusicgod1** [comment] 2015-07-01 06:27
Reproduced in xfce

**Comment by trav90** [comment] 2015-10-03 05:08
Can this issue be closed as well, as it could not be reproduced by anyone except the OP, and there has been no followup?

**Comment by wolfbeast** [comment] 2015-10-03 19:43
Will close this for now. without more information there's no way to provide a fix.

**Closed by wolfbeast** 2015-10-03 19:43 UTC
Labels: Linux, more info needed, worksforme

**Comment by themusicgod1** [comment] 2015-10-12 17:19
I reproduced in two desktop managers(gnome/xfce), so it's not the desktop manager.

**Comment by Axiomatic-** [comment] 2015-10-14 23:35
@themusicgod1 it likely is not the desktop manager, however no one seems to be able to duplicate your issue. Ubuntu is known for breaking certain de-facto standards maybe your issue has a relation to that. (Though no other Ubuntu users seem to have your issue.) 

Next time this happens can you do ```xprop | grep WM_CLASS``` in your terminal of choice, and then copy, and paste the output into a gist. Also if you can try a different distro (I am not expecting you to change your distro, just curious if you can duplicate the issue on another distro.)

**Comment by chaoskagami** [comment] 2015-10-15 17:29
As a weird question, @themusicgod1, do you use compiz? Or another compositor? Also, do you use any IME software (Like IBUS, etc?) Have you messed with anything in /etc on your system?

Maybe it isn't really relevant, but it is a thought. Compositing managers sometimes do weird things, and input methods can cause oddities with regard to focus. It doesn't even matter if you're using the IME, btw. Just being enabled can cause issues. And changing default configurations with blob distros is somewhat no-no.

@Axiomatic-, Ubuntu certainly doesn't obey standards, but it's compliant enough that it shouldn't be that. It's so easy to blame Ubuntu (I do it too) but I believe this a misconfiguration of some sort.

I rebuilt my entire system and I still can't repro your issue @themusicgod1. And I regularly rebuild Pale Moon from git as well, so not sure what to tell you. Have you run `apt-get update && apt-get upgrade` recently? Do you use any third party repositories/PPAs?

**Comment by themusicgod1** [comment] 2015-10-15 19:04
(Actually I am usually running 2-3 different distros but have only managed to reproduce in ubuntu 15.10 thus far).  I'm totally ok with blaming ubuntu and do apt-get update weeklyish.  I do have a few third party repos:
 
deb http://ppa.launchpad.net/ginggs/motif1565/ubuntu vivid main
deb http://ppa.launchpad.net/ginggs/motif1565/ubuntu wily main 
deb-src http://ppa.launchpad.net/ginggs/motif1565/ubuntu vivid main
deb-src http://ppa.launchpad.net/ginggs/motif1565/ubuntu wily main

(as an aside, it might be time to remove those, since I think the changes they were for made their way into the main branch of ubuntu)

compiz: no

ibus: yes but might have reproduced without ibus already(since there's another 'bug' involving ibus in firefox (and probably palemoon) that I uninstalled ibus during this time period https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1421483 ).  I will try to verify this.

Have you messed with anything in /etc on your system?  Yes (custom hosts file...not sure how I'd even list all my customizations in /etc/ outside of that).

Note: since upgrading to d38679b I have not been able to reproduce.  Will continue to try to reproduce.

**Comment by chaoskagami** [comment] 2015-10-16 04:40
It could be ibus. I remember having similar issues a while ago with firefox and ibus. For /etc, I'm more concerned with X and backend-ish configs like graphical settings and desktop settings. Hosts isn't an issue; I regularly rebuild mine from MVPS, Pgl, and someonewhocares.

Also, the PPA you listed is a 404 not found. Better off just removing it. ;P

**Comment by Axiomatic-** [comment] 2015-10-17 19:45
I used to use IBus to type in Japanese on Lang-8 and multiple image-boards (2ch, etc) through Pale Moon and had no issues. However it has been awhile, I will check to see if I can reproduce anything myself with IBus. 

Since upgrading to a newer version of Pale Moon, did you by chance upgrade GCC? @themusicgod1

**Comment by themusicgod1** [comment] 2015-10-22 11:03
Yeah I did.  I'm up to gcc 5.2 now.

**Comment by Axiomatic-** [comment] 2015-10-23 01:33
It sounds likely that some package fixed something that was broken with it, and caused interference with Pale Moon. Does Ubuntu have a roll back feature? If it does try compiling with GCC 4.9.2, if you can reproduce the issue, then this bug can be marked as a compiler bug. (I have no luck getting IBus to reproduce what you describe for text input getting stuck; however, I did come across some other issues.)

**Comment by chaoskagami** [comment] 2015-10-23 03:21
I use GCC 5.2 on my system, and while it has severe issues with precompiled headers it exhibits no issues with PM.  Not gcc.

**Comment by Axiomatic-** [comment] 2015-10-23 03:31
I meant GCC 4.9.2, not GCC 5.2. :-P

**Comment by chaoskagami** [comment] 2015-10-23 18:12
This is why I shouldn't post comments to bug reports before I snooze for the day. :P

Out of curiousity, @themusicgod1, what's in your mozconfig?

**Comment by themusicgod1** [comment] 2015-10-23 18:38
ac_add_options --disable-tests
ac_add_options --disable-mochitests
ac_add_options --disable-jemalloc

ac_add_options --enable-optimize="-O2 -march=native -mfpmath=sse"

mk_add_options MOZ_MAKE_FLAGS="-j6"

**Comment by chaoskagami** [comment] 2015-10-23 23:21
I'm not really seeing anything stand out...I don't think we'll ever know what caused this. It might be best to chock it up to a bug in *something*. You aren't linking against system libraries, which makes this all the more weird.

My config is below, if it helps debug this somehow.

export PYENV=2
mk_add_options MOZ_CO_PROJECT=browser
mk_add_options AUTOCLOBBER=1
ac_add_options --enable-application=browser
ac_add_options --disable-installer
ac_add_options --disable-updater
ac_add_options --disable-necko-wifi
ac_add_options --disable-crashreporter
ac_add_options --disable-dbus
ac_add_options --disable-tests
ac_add_options --disable-mochitests
ac_add_options --disable-jemalloc
ac_add_options --with-system-cairo
ac_add_options --with-system-pixman
ac_add_options --enable-strip
ac_add_options --enable-install-strip
ac_add_options --disable-debug
ac_add_options --disable-pulseaudio
mk_add_options PYTHON=/usr/bin/python2
mk_add_options AUTOCONF=/arch/ver/autoconf/2.13/bin/autoconf
ac_add_options --enable-crypto
ac_add_options --enable-gstreamer
mk_add_options MOZ_MAKE_FLAGS="-j4"
ac_add_options --enable-optimize="-O2 -march=native"
ac_add_options --enable-system-sqlite
ac_add_options --with-system-libevent
ac_add_options --with-system-libvpx
ac_add_options --with-system-libwebp
ac_add_options --with-system-nspr
ac_add_options --with-system-nss
ac_add_options --with-system-icu
ac_add_options --with-system-ffi
ac_add_options --with-pthreads
ac_add_options --with-system-bz2
ac_add_options --with-system-jpeg
ac_add_options --with-system-png
ac_add_options --with-system-zlib
ac_add_options --prefix=/usr

**Comment by Axiomatic-** [comment] 2015-10-25 03:25
Not really, as you cannot reproduce the bug, correct?

You can do a little cleaning for your .mozconfig though.
Remove: 
--enable-crypto (as the configure only supports disable, and crypto is enabled by default).
--with-system-icu (the configure.in has no reference to this, so it is likely ignored).


Change:
--with-system-libwebp to [--with-system-webp](https://github.com/MoonchildProductions/Pale-Moon/blob/master/configure.in#L3921) (the hyper-link shows the reference in configure.in).

A suggestion:
Add mfpmath=sse to your enable optimize line (by default builds use it, I would not rely on that GCC enables it by default mainly because GCC can be odd at times), if you are feeling to test GCC try using mfpmath=both.

**Comment by themusicgod1** [comment] 2015-10-26 18:02
@Axiomatic- looking more closely, although I upgraded to a new gcc on my system as a whole, palemoon still got compiled with 4.9.2 according to about:buildconfig Go figure.

**Comment by themusicgod1** [comment] 2015-10-27 01:20
...reproduced with gcc 4.9.2 in commit d38679b

**Comment by themusicgod1** [comment] 2015-10-27 01:23
...will try to reproduce without ibus/with gcc-5 next but I'm kind of stuck using this computer as a lifeline atm so I'll have to find somewhere else I can test on.

**Comment by chaoskagami** [comment] 2015-10-27 01:52
You could try it in a chroot, with a different distro like a gentoo stage3, or with a debootstrap system. Just make sure to copy your Xorg cookies.

@Axiomatic- Yeah, can't repro it. I've updated by mozconfig to not pass useless flags as per your suggestions, so thanks. I'll read through the Makefile.in later. As for the `-mfpmath` suggestion, according to GCC 5.2's manpage, `-mfpmath=sse` is the default option for x86-64 unless otherwise specified. I'm going to avoid `-mfpmath=both` because of the notes on CPU use; I'm constantly multitasking so I'd rather PM not starve other things.

**Comment by themusicgod1** [comment] 2016-01-23 02:59
Reproduced without ibus

**Comment by themusicgod1** [comment] 2016-01-24 03:27
Reproduced in build made by gcc-5.  Will try openbox next.

**Comment by themusicgod1** [comment] 2016-01-24 18:09
Reproduced in xfce.

Ubuntu: 15.10
xfce4:
  Installed: 4.12.1
  Candidate: 4.12.1

**Comment by themusicgod1** [comment] 2016-01-24 18:09
Will try in another linux distro (probably tails) next.

**Comment by wolfbeast** [comment] 2016-01-24 18:59
Instead of trying to reproduce it on different flavors, why don't you try to figure out what you have common between them that others who can't reproduce it don't have? Is there something specific you always do when you set up an environment? Do you have non-default drivers for input? etc. etc. etc.
