### ISSUE TITLE
100% repeatable SIGSEGV 0x00007efd1fbf463d in mozalloc_abort

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#354] opened 2016-02-07 19:58 UTC
ubuntu: 15.10
palemoon commit: dab2fee

to reproduce: 
1) visit http://blockchainbdgpzk.onion/
2) click 'wallet'
3) login with credentials, doesn't seem to matter if they are correct or not.

boom! segfault.  Been doing this for awhile .

Program received signal SIGSEGV, Segmentation fault.
0x00007efd1fbf463d in mozalloc_abort (msg=0x7efd1e577d98 "Trying to allocate an infallible array that's too big")
    at /home/themusicgod1/palemoon/Pale-Moon/memory/mozalloc/mozalloc_abort.cpp:30
30	    MOZ_CRASH();

current .mozconfig:

export HOST_CC=gcc-5
export HOST_CXX=g++-5
export CC="gcc-5  $FLAGS"
export CXX="g++-5  $FLAGS"
export CPP="cpp-5  $FLAGS"
ac_add_options --disable-vp8
ac_add_options --disable-tests
ac_add_options --disable-mochitests
ac_add_options --disable-jemalloc
export MOZ_DEBUG_SYMBOLS=1
ac_add_options --enable-debug-symbols="-gdwarf-2"
ac_add_options --enable-optimize="-march=native -mfpmath=sse"
mk_add_options MOZ_MAKE_FLAGS="-j4"

pretty sure it was doing it with gcc 4.9 & debugging turned off too (But I wanted the stack trace:)

 stack trace : http://0bin.net/paste/6CmKdCPNQalIGWKz#hIJeJ+IzjLVvAEUENyW0w0M8AHvpR8COu7xO8xZxwIl
more details on top few frames:
http://0bin.net/paste/f9B449Sd-zQKo9Hb#p9wquhPU3g-PyWq1/gwCAkG2OlQ1RGRlWpYtEyL7Ct6

**Comment by wolfbeast** [comment] 2016-02-07 20:27
Since it's an .onion address there's no easy way for me to reproduce and attach a debugger to it.

**Comment by themusicgod1** [comment] 2016-02-07 20:30
might work on https://blockchain.info too but I can't reproduce there (as it kicks you to the .onion address if you try)

**Comment by wolfbeast** [comment] 2016-02-07 20:33
The top frames do help, but it makes no sense. It's part of the code that deals with transparent gradients, and it apparently loops on inserting until it runs out of memory. I'll g over the logic there with another fine toothed comb but I thought I had all contingencies addressed.

**Comment by wolfbeast** [comment] 2016-02-07 20:41
oh.. I just realized you're using a commit that doesn't have a known issue addressed.
You need to apply commit 4cda4e3bd10d2b5d49b2c1cff8c26f99d9f4b367 as well. Why aren't you using a more recent commit?

**Comment by wolfbeast** [comment] 2016-02-07 21:52
Duplicate of #339

**Closed by wolfbeast** 2016-02-07 21:52 UTC
Labels: Duplicate
