### ISSUE TITLE
The profile - resetting (migration doesn't work)

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1480] opened 2017-11-18 14:35 UTC
Ad:
https://forum.palemoon.org/viewtopic.php?f=3&t=17353

__Steps to reproduce:__
Main menu: `Tools` - `Troubleshooting Information` - `Refresh Pale Moon`

__Actual results:__
Migrate doesn't work: bookmarks, cookies, passwords...

__Expected results:__
Migration works properly.

__Affected versions:__
all (if it is an another profile than `Default`)

**Comment by wolfbeast** [comment] 2017-11-19 10:31
I really don't have a setup to test this, so if anyone else could, that would be great!

**Comment by wolfbeast** [comment] 2017-12-26 10:05
Can this be closed? Has anyone tested this?

**Comment by janekptacijarabaci** [comment] 2017-12-26 19:13
IMHO yes, if no one else will test it...

**Comment by SpockMan02** [comment] 2018-01-11 23:28
`Help` -> `Troubleshooting Information`, `Refresh Pale Moon...` Restarts, replacing profile, old profile contained within `Old Pale Moon Data` folder on desktop. Custom-set bookmarks not present in new profile. Does this confirm the bug, or is this expected behavior? Pale Moon 27.6.2 (64-bit) on macOS 10.12.6

**Comment by wolfbeast** [comment] 2018-01-12 01:30
> Migrate doesn't work: bookmarks, cookies, passwords...

Not very clear what constitutes "doesn't work" or what expected behavior would be.

**Comment by mattatobin** [comment] 2018-01-12 02:21
Is resetting the profile supposed to retain data? Or is it a factory reset that is basically an automated function to backup, delete, and create a new profile.. Best to test this with Firefox or at least Basilisk to establish intended behavior.

**Comment by janekptacijarabaci** [comment] 2018-01-12 06:00
@SpockMan02
`Pale Moon 27.6.2 (64-bit)` - this bug isn't fixed in version 27.6.2

**Comment by mattatobin** [comment] 2018-01-12 11:45
Assuming this ever was a bug. .. Wait.. 27.6........ ugh

**Comment by SpockMan02** [comment] 2018-01-12 18:11
On Firefox 56.0.2, `Help` -> `Troubleshooting Information`, `Refresh Firefox...` Closes Firefox, briefly shows a small window called `Import Wizard` which says
>**Import Complete**
>The following items were successfully imported:
>Cookies
>Browsing History and Bookmarks
>Saved Form History
>Saved Passwords
>Other Data
>Windows and Tabs

`Cancel` (greyed out) `Go Back` (greyed out) `Done`
The window disappears after a few seconds, and Firefox restarts with two tabs open, a `Success!` page that states that add-ons and customizations have been removed and settings have been restored to their defaults, with the option to `Restore all windows & tabs` or `Restore only the ones you want`, and the Firefox Privacy Notice page (https://www.mozilla.org/en-US/privacy/firefox/).

**Comment by SpockMan02** [comment] 2018-01-12 23:08
Okay, here's an idea. How about we rename `Refresh Pale Moon...` to something like `Replace profile`? That would be more descriptive of what it does. We already have Safe Mode, and we could add something in `Preferences` -> `General` or `Advanced` to reset all preferences. Then, we'd have all the same functionality.

Slightly off-topic: I don't like how Mozilla touts "refreshing" as something that should be done to make your browser work better; for example, when you haven't started Firefox in a while, it'll tell you that you should do it. But all it does (in Firefox) is get rid of all your add-ons and reset all your preferences, which, while it may solve some problems, should not be advertized as some panacea.

**Comment by wolfbeast** [comment] 2018-01-12 23:45
Restricting comments -- this isn't a forum or a free-for-all suggestions area or place to toss out your random thoughts/opinions. If you want to discuss development issues, see our forum, we have a dedicated board for that stuff.

**Comment by wolfbeast** [comment] 2018-01-12 23:46
considering verified on unstable, closing.

**Closed by wolfbeast** 2018-01-12 23:46 UTC
Labels: Verification Needed
