### ISSUE TITLE
Allow icon fonts to override user font setting

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#129] opened 2015-07-18 22:03 UTC
Ensure that icon fonts can be viewed even when the user has set their own fonts to display (fixes issue described [here] (https://forum.palemoon.org/viewtopic.php?f=13&t=8511)).

BMO: [789788] (https://bugzilla.mozilla.org/show_bug.cgi?id=789788).

**Comment by wolfbeast** [comment] 2015-07-19 12:39
It's rather tricky because it's difficult to determine when something is an "icon font". I don't particularly like the "solution" Firefox has implemented in their patch in that bug, either. it's making a lot of assumptions.

Also, asking the question "why are people actually using the font override?" is important. Is it because they simply "don't like" certain web fonts, and don't care that the website will no longer look as intended? Or is it because the text font choices to go along with icon fonts are actually so terrible it becomes unreadable?

**Comment by wolfbeast** [comment] 2015-07-19 12:52
I think the only 2 real options to avoid this issue is to either not allow overrides, period (which really isn't an option for Pale Moon, even though some other browsers like Chrome and Opera don't have this long-standing and rather archaic option anymore) or to only allow overrides when the font used on the website either has a listed generic fallback or has a generic family it belongs to.

**Comment by Lootyhoof** [comment] 2015-07-19 13:22
The Firefox patch makes assumptions, but mainly because it's out of necessity, it seems. From the looks of it, most of these icon fonts use glyphs in the Unicode PUA (mainly to avoid tripping up screen readers, I believe), so they just would not display if not using the font specified. Using a fallback in this case simply isn't possible.

**Comment by Lootyhoof** [comment] 2015-07-19 13:43
In particular, see [FontAwesome] (http://fontawesome.io/), one of the more popular icon fonts, which is also incorporated into the Bootstrap framework (and probably others too, at this point).

**Comment by wolfbeast** [comment] 2015-07-19 13:48
Hmm no, I don't think that icon fonts always use the Unicode PUA. Like I said though, only allowing an override when a font *has* a fallback listed or *is* part of a generic family (as indicated in the font itself, **which an icon font should never, ever do**) would be a solution; and would be fairly simple to implement for the small percentage of users that actually do have issues with web fonts' readability (e.g. people needing OpenDyslexic or having eyesight issues needing serif fonts (as in the person making the forum thread) when everyone drools over sans).

It'll be similar to Firefox's solution as far as detection goes, but I'm not going to mess with the order of font lists to enforce my own preference like FF does.

**Comment by wolfbeast** [comment] 2015-07-19 14:37
Commit bc01bb1 should fix all this :)

**Comment by wolfbeast** [comment] 2015-07-19 15:10
Decided to port this across to 25.6 since it's a usability issue, the patch is straightforward, and seems to work as-intended.

**Comment by wolfbeast** [comment] 2015-07-19 18:16
Confirmed fixed on latest master, setting document fonts to false and choosing serif as default font. Icon fonts from fontawesome still work on start.me.

![iconfont1](https://cloud.githubusercontent.com/assets/3359132/8767132/e20921ae-2e52-11e5-9a9f-79169d0675aa.jpg)

**Closed by wolfbeast** 2015-07-19 18:16 UTC
Labels: enhancement
