### ISSUE TITLE
Website Corruption & Crashes & High CPU usage

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/Pale-Moon#821] opened 2017-01-10 22:08 UTC
Since today, i see the following issues including high cpu usage:

Sites, Palemoon corrupts:
https://web.whatsapp.com/

Sites, Palemoon crashes:
https://web.whatsapp.com/ (on reload)
http://www.golem.de/ (After loading the advertising, which is not blocked with Adblock Latitude "Easy Filterlist (Germany)"???!!!)

Linux mint 18.1 x64
Palemoon 27.0.3 (x64)

Addons:
Adblock Latitude	4.0.0	true	adblocklatitude@addons.palemoon.org
Browser-Add-on zur Deaktivierung von Google Analytics	0.9.8	true	{6d96bb5e-1175-4ebf-8ab5-5f56f1c79f65}
DownThemAll!	2.0.18.1-signed.1-let-fixed	true	{DDC359D1-844A-42a7-9AA1-88A850A938A8}
Encrypted Web	5.1.5	true	{4bf973fe-f2b7-43e1-b2ca-52f9c6f6fddf}
NoScript	2.9.0.14	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
OpenDownload²	4.1.2	true	{210249CE-F888-11DD-B868-4CB456D89593}
QR Code	1.1.12.1-signed.1-signed	true	{6a910736-6fab-4480-841a-36325cce134f}

Wichtige modifizierte Einstellungen
Name 	Wert accessibility.typeaheadfind.flashBar	0
browser.cache.disk.capacity	358400
browser.cache.disk.smart_size_cached_value	307200
browser.cache.disk.smart_size.first_run	false
browser.cache.disk.smart_size.use_old_max	false
browser.cache.frecency_experiment	3
browser.download.importedFromSqlite	true
browser.places.smartBookmarksVersion	7
browser.search.useDBForOrder	true
browser.sessionstore.upgradeBackup.latestBuildID	20150125222008
browser.startup.homepage_override.buildID	20161229201427
browser.startup.homepage_override.mstone	3.0.3
browser.zoom.full	false
dom.mozApps.used	true
extensions.lastAppVersion	27.0.3
general.useragent.locale	de
media.gmp-gmpopenh264.lastUpdate	1423248305
media.gmp-gmpopenh264.version	1.3
media.gmp-manager.lastCheck	1423615072
network.cookie.prefsMigrated	true
places.database.lastMaintenance	1484052372
places.history.expiration.transient_current_max_pages	104858
plugin.disable_full_page_plugin_for_types	application/pdf
plugin.importedState	true
print.print_bgcolor	false
print.print_bgimages	false
print.print_colorspace	default
print.print_downloadfonts	false
print.print_evenpages	true
print.print_in_color	true
print.print_margin_bottom	0.5
print.print_margin_left	0.5
print.print_margin_right	0.5
print.print_margin_top	0.5
print.print_oddpages	true
print.print_orientation	0
print.print_page_delay	50
print.print_paper_data	0
print.print_paper_height	279,40
print.print_paper_name	na_letter
print.print_paper_size_type	1
print.print_paper_size_unit	1
print.print_paper_width	215,90
print.print_plex_name	default
print.print_resolution_name	default
print.print_scaling	1,00
print.print_shrink_to_fit	true
print.print_to_file	false
print.print_unwriteable_margin_bottom	56
print.print_unwriteable_margin_left	25
print.print_unwriteable_margin_right	25
print.print_unwriteable_margin_top	25
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_colorspace	false
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_downloadfonts	false
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_jobtitle	false
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_num_copies	true
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_orientation	true
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_paper_size	true
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_plex	false
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_printincolor	true
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_resolution	false
print.tmp.printerfeatures.CUPS/Officejet_6600.can_change_spoolercommand	false
print.tmp.printerfeatures.CUPS/Officejet_6600.colorspace.0.name	default
print.tmp.printerfeatures.CUPS/Officejet_6600.colorspace.count	1
print.tmp.printerfeatures.CUPS/Officejet_6600.has_special_printerfeatures	true
print.tmp.printerfeatures.CUPS/Officejet_6600.orientation.0.name	portrait
print.tmp.printerfeatures.CUPS/Officejet_6600.orientation.1.name	landscape
print.tmp.printerfeatures.CUPS/Officejet_6600.orientation.count	2
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.0.height_mm	210
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.0.is_inch	false
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.0.name	A5
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.0.width_mm	148
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.1.height_mm	297
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.1.is_inch	false
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.1.name	A4
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.1.width_mm	210
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.2.height_mm	420
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.2.is_inch	false
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.2.name	A3
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.2.width_mm	297
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.3.height_mm	279
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.3.is_inch	true
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.3.name	Letter
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.3.width_mm	215
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.4.height_mm	355
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.4.is_inch	true
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.4.name	Legal
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.4.width_mm	215
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.5.height_mm	431
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.5.is_inch	true
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.5.name	Tabloid
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.5.width_mm	279
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.6.height_mm	254
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.6.is_inch	true
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.6.name	Executive
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.6.width_mm	190
print.tmp.printerfeatures.CUPS/Officejet_6600.paper.count	7
print.tmp.printerfeatures.CUPS/Officejet_6600.plex.0.name	default
print.tmp.printerfeatures.CUPS/Officejet_6600.plex.count	1
print.tmp.printerfeatures.CUPS/Officejet_6600.resolution.0.name	default
print.tmp.printerfeatures.CUPS/Officejet_6600.resolution.count	1
print.tmp.printerfeatures.CUPS/Officejet_6600.supports_colorspace_change	false
print.tmp.printerfeatures.CUPS/Officejet_6600.supports_downloadfonts_change	false
print.tmp.printerfeatures.CUPS/Officejet_6600.supports_jobtitle_change	false
print.tmp.printerfeatures.CUPS/Officejet_6600.supports_orientation_change	true
print.tmp.printerfeatures.CUPS/Officejet_6600.supports_paper_size_change	true
print.tmp.printerfeatures.CUPS/Officejet_6600.supports_plex_change	false
print.tmp.printerfeatures.CUPS/Officejet_6600.supports_printincolor_change	true
print.tmp.printerfeatures.CUPS/Officejet_6600.supports_resolution_change	false
print.tmp.printerfeatures.CUPS/Officejet_6600.supports_spoolercommand_change	false
privacy.donottrackheader.enabled	true
privacy.sanitize.migrateFx3Prefs	true
storage.vacuum.last.index	1
storage.vacuum.last.places.sqlite	1481807386

Installierte Plugins
Updates für installierte Plugins finden Sie auf mozilla.com/plugincheck
IcedTea-Web Plugin (using IcedTea-Web 1.6.2 (1.6.2-3ubuntu1))

    Datei: IcedTeaPlugin.so
    Pfad: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/IcedTeaPlugin.so
    Version: 
    Status: Aktiviert
    The IcedTea-Web Plugin executes Java applets.

MIME-Typ	Beschreibung	Endungen
application/x-java-vm	IcedTea	class,jar
application/x-java-applet	IcedTea	class,jar
application/x-java-applet;version=1.1	IcedTea	class,jar
application/x-java-applet;version=1.1.1	IcedTea	class,jar
application/x-java-applet;version=1.1.2	IcedTea	class,jar
application/x-java-applet;version=1.1.3	IcedTea	class,jar
application/x-java-applet;version=1.2	IcedTea	class,jar
application/x-java-applet;version=1.2.1	IcedTea	class,jar
application/x-java-applet;version=1.2.2	IcedTea	class,jar
application/x-java-applet;version=1.3	IcedTea	class,jar
application/x-java-applet;version=1.3.1	IcedTea	class,jar
application/x-java-applet;version=1.4	IcedTea	class,jar
application/x-java-applet;version=1.4.1	IcedTea	class,jar
application/x-java-applet;version=1.4.2	IcedTea	class,jar
application/x-java-applet;version=1.5	IcedTea	class,jar
application/x-java-applet;version=1.6	IcedTea	class,jar
application/x-java-applet;version=1.7	IcedTea	class,jar
application/x-java-applet;version=1.8	IcedTea	class,jar
application/x-java-applet;jpi-version=1.8.0_50	IcedTea	class,jar
application/x-java-bean	IcedTea	class,jar
application/x-java-bean;version=1.1	IcedTea	class,jar
application/x-java-bean;version=1.1.1	IcedTea	class,jar
application/x-java-bean;version=1.1.2	IcedTea	class,jar
application/x-java-bean;version=1.1.3	IcedTea	class,jar
application/x-java-bean;version=1.2	IcedTea	class,jar
application/x-java-bean;version=1.2.1	IcedTea	class,jar
application/x-java-bean;version=1.2.2	IcedTea	class,jar
application/x-java-bean;version=1.3	IcedTea	class,jar
application/x-java-bean;version=1.3.1	IcedTea	class,jar
application/x-java-bean;version=1.4	IcedTea	class,jar
application/x-java-bean;version=1.4.1	IcedTea	class,jar
application/x-java-bean;version=1.4.2	IcedTea	class,jar
application/x-java-bean;version=1.5	IcedTea	class,jar
application/x-java-bean;version=1.6	IcedTea	class,jar
application/x-java-bean;version=1.7	IcedTea	class,jar
application/x-java-bean;version=1.8	IcedTea	class,jar
application/x-java-bean;jpi-version=1.8.0_50	IcedTea	class,jar
application/x-java-vm-npruntime	IcedTea	
DivX® Web Player

    Datei: libxplayer-mully-plugin.so
    Pfad: /usr/lib/mozilla/plugins/libxplayer-mully-plugin.so
    Version: 
    Status: Aktiviert
    DivX Web Player version 1.4.0.233

MIME-Typ	Beschreibung	Endungen
video/divx	AVI-Video	divx
VLC Multimedia Plugin (compatible Videos 1.2.2)

    Datei: libxplayer-cone-plugin.so
    Pfad: /usr/lib/mozilla/plugins/libxplayer-cone-plugin.so
    Version: 
    Status: Aktiviert
    The Videos 1.2.2 plugin handles video and audio streams.

MIME-Typ	Beschreibung	Endungen
application/x-vlc-plugin	VLC Multimedia Plugin	
application/vlc	VLC Multimedia Plugin	
video/x-google-vlc-plugin	VLC Multimedia Plugin	
application/x-ogg	Ogg-Multimediadatei	ogg
application/ogg	Ogg-Multimediadatei	ogg
audio/ogg	Ogg-Audio	oga
audio/x-ogg	Ogg-Audio	ogg
audio/x-vorbis+ogg	Ogg-Vorbis-Audio	ogg
video/ogg	Ogg-Video	ogv
video/x-ogg	Ogg-Video	ogg
video/x-theora+ogg	Ogg-Theora-Video	ogg
application/annodex	Annodex-Wechselformat	anx
audio/annodex	Annodex-Audio	axa
video/annodex	Annodex-Video	axv
video/mpeg	MPEG-Video	mpg, mpeg, mpe
audio/wav	WAV-Audio	wav
audio/x-wav	WAV-Audio	wav
audio/mpeg	MP3-Audio	mp3
application/x-nsv-vp3-mp3	NullSoft-Video	nsv
video/flv	Flash-Video	flv
video/webm	WebM-Video	webm
application/x-xplayer-plugin	Videos multimedia plugin	
audio/midi	MIDI-Audio	mid, midi
QuickTime Plug-in 7.6.6

    Datei: libxplayer-narrowspace-plugin.so
    Pfad: /usr/lib/mozilla/plugins/libxplayer-narrowspace-plugin.so
    Version: 
    Status: Aktiviert
    The Videos 1.2.2 plugin handles video and audio streams.

MIME-Typ	Beschreibung	Endungen
video/quicktime	QuickTime-Video	mov
video/mp4	MPEG-4-Video	mp4
image/x-macpaint	MacPaint-Bitmap-Datei	pntg
image/x-quicktime	Macintosh-Quickdraw/PICT-Zeichnung	pict, pict1, pict2
video/x-m4v	MPEG-4-Video	m4v
application/vnd.apple.mpegurl	HTTP Live-Streaming-Wiedergabeliste	m3u8
Windows Media Player Plug-in 10 (compatible; Videos)

    Datei: libxplayer-gmp-plugin.so
    Pfad: /usr/lib/mozilla/plugins/libxplayer-gmp-plugin.so
    Version: 
    Status: Aktiviert
    The Videos 1.2.2 plugin handles video and audio streams.

MIME-Typ	Beschreibung	Endungen
application/x-mplayer2	AVI-Video	avi, wma, wmv
video/x-ms-asf-plugin	ASF-Video	asf, wmv
video/x-msvideo	AVI-Video	asf, wmv
video/x-ms-asf	ASF-Video	asf
video/x-ms-wmv	Windows-Media-Video	wmv
video/x-wmv	Windows-Media-Video	wmv
video/x-ms-wvx	Windows-Media-Video	wmv
video/x-ms-wm	Windows-Media-Video	wmv
video/x-ms-wmp	Windows-Media-Video	wmv
application/x-ms-wms	Windows-Media-Video	wms
application/x-ms-wmp	Windows-Media-Video	wmp
application/asx	Microsoft-ASX-Wiedergabeliste	asx
audio/x-ms-wma	Windows-Media-Audio	wma
Shockwave Flash

    Datei: libflashplayer.so
    Pfad: /usr/lib/adobe-flashplugin/libflashplayer.so
    Version: 
    Status: Aktiviert
    Shockwave Flash 24.0 r0

MIME-Typ	Beschreibung	Endungen
application/x-shockwave-flash	Shockwave Flash	swf
application/futuresplash	FutureSplash Player	spl

**Comment by wolfbeast** [comment] 2017-01-10 23:31
Does this still occur if you disable the libxplayer plugin?

**Comment by MartinX3** [comment] 2017-01-11 14:20
How i can get crash logs?

I set every plugin now to "ask, if want to be used", the error still occur.

With corruption, i mean, as example of whatsapp web, after a while of using:
I click on message details and instead of seeing at which time, the message got read, i see a gif animation, sent prior i another conversation.

Or i still see the message informations of another message, not from the message i clicked on.

And every animation is slow, like expanding.

**Comment by wolfbeast** [comment] 2017-01-11 16:29
@trav90 Maybe you can help this user collect some details or offer suggestions - I'm out of my depth on this one.

Incorrect message details would be something inside the whatsapp web application going awry. That is likely unrelated to Pale Moon.
The error message in the terminal seems to be gstreamer related.
I can't really help with the German here. "speicher" is rather ambiguous.

**Comment by trav90** [comment] 2017-01-12 04:19
Based on the terminal message reported above it appears to be another GStreamer related crash.  @MartinX3 can you reproduce the crash if the "media.gstreamer.enabled" pref is set to false?

**Comment by MartinX3** [comment] 2017-01-12 15:03
The message
** (pale moon:6862): CRITICAL **: gst_app_src_set_size: assertion 'GST_IS_APP_SRC (appsrc)' failed
disappeared.

But it still crash with this message
Speicherzugriffsfehler

And it happens on this site, too
http://www.golem.de/news/egosoft-update-4-0-mit-stellaren-neuen-funktionen-fuer-x-rebirth-1602-119412.html

**Comment by trav90** [comment] 2017-01-12 22:06
Can't reproduce here. Are you using binaries from linux.palemoon.org or Steve Pusser's PPA?

**Comment by MartinX3** [comment] 2017-01-13 09:37
I use the PPA from Steven Pusser <stevep@mxlinux.org>
Version 27.0.3~repack-2

**Comment by trav90** [comment] 2017-01-13 14:58
The binaries from the PPA have been built with GCC 5 which introduces some instabilities. I'm working with Steve to get this fixed.

**Comment by MartinX3** [comment] 2017-01-13 18:37
THANK YOU!
That would be fantastic!
Better to use the stable v4. :dancer: 

By the way:
When I have time, I will make a FossMail PPA.
I think i will get in touch with Steve to finish that.
But now, i will have final exams at the end of the month and there is no really free time to do this.

**Comment by rea987** [comment] 2017-01-13 20:13
I confirm that twitch.tv hard-crashes "Repositories for Debian and Ubuntu" (opensuse.org) version of Pale Moon 27.0.3 (x64) on Linux Mint 18.1 regardless of MSE settings. Purging the installation and switching the Linux installer (pminstaller.sh) mostly solved the issue.

**Comment by wolfbeast** [comment] 2017-01-16 01:39
@trav90 Please let me know if you make any progress with Steve to use a sane build environment. If these continue to cause issues because of unwillingness to produce stable binaries with a sane config, then let me know, and I'll have to revoke his permission to use official branding.

**Comment by trav90** [comment] 2017-01-16 05:31
@wolfbeast will do. I sent Steve a message early this morning and am awaiting his response.

**Comment by trav90** [comment] 2017-01-23 15:38
Closing this issue since we no longer endorse the 3rd party builds that these crashes happen in.

**Closed by trav90** 2017-01-23 15:38 UTC
Labels: Linux

**Comment by MartinX3** [comment] 2017-01-23 16:35
Oh shit, Steve gave you no response?
That's very bad, i prefer repos, because te update notification and the easier update process....

**Comment by trav90** [comment] 2017-01-23 19:45
We would still be happy to work with Steve but at this point we can't endorse these builds any longer as they are harming Pale Moon's reputation. Hopefully he will be in contact with either Moonchild or myself soon.

**Comment by wolfbeast** [comment] 2017-01-24 03:51
Most *nix users prefer repos and package managers for good reason -- also the reason why our Linux builds done have an automatic update system unlike the Windows builds (since it's assumed different distros can and will use the designated package management options).

Unfortunately, since these are built from source with an obviously not-kosher build setup, instead of 9what some other maintainers/distros do) using the binary tarballs and repackaging or similar, the binaries here are out of our control and I'm done taking the fall-out of it or letting it give a really bad impression to Ubuntu/Debian users in general.

I've asked the OpenSUSE folks to remove the packages as well since there's been 0 response from Steve, and as said these binaries are harming Pale Moon's reputation.

**Comment by MartinX3** [comment] 2017-01-24 11:09
Thanks for your help!

Please update this thread, if Steve did response!

**Comment by trav90** [comment] 2017-01-31 08:57
@MartinX3 @rea987 I have been working with Steve and believe that we have resolved this issue. Can you please install the "newmoon" packages from his repo and report back if the crashes reported here still occur? Thanks.

https://forum.palemoon.org/viewtopic.php?f=37&t=14586#p104688

**Comment by MartinX3** [comment] 2017-01-31 12:22
the newmoon in the ppa is only 32-bit
instead of be like palemoon 64bit

so i don't know, if it works as 64-bit version, too.

And btw.
i can't test it, because it wants to delete
gstreamer1.0-plugins-ugly
libsidplay1v5
mint-meta-codecs
mint-meta-codecs-core
palemoon

it want to remove these and replace them with tzhe :i386 version alongside of 100 new libs.
wtf
sorry, i don't want to crash my Linux Mint 18.1 x64 Mate

**Comment by MartinX3** [comment] 2017-01-31 22:15
Now, I'm facing a CPU load of ~276% on my quadcore.
And my CPU rises its clockspeed to its maximum and warmed up to 90°C.
40°C is normal.
Argh.

**Comment by trav90** [comment] 2017-02-01 05:08
So.. I'm confused. Are the newmoon builds working or not?

**Comment by MartinX3** [comment] 2017-02-01 15:34
No more crashes, but my CPU load is very high while using 23 tabs.
My Quadcore CPU load at 70% on every core, my CPU fan is at 100% and the core temperature is at 90°C

**Comment by MartinX3** [comment] 2017-02-05 15:55
Since today, loading a facebookprofile freezes my browser and then it consumes 100% on one CPU core.

**Comment by MartinX3** [comment] 2017-02-09 20:35
Holy shit, every time, i open a facebook site, my cpu fan speed up very loudly and the cpu usage is very high.

**Comment by wolfbeast** [comment] 2017-02-09 20:53
Yes we get it. Please stop repeating the same information.

**Comment by wolfbeast** [comment] 2017-02-09 20:55
Restricting comments since this issue is closed and we've worked with the distro supplier to get a sane build going.
