### ISSUE TITLE
Opening a new window on about:blank should focus on the address bar.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1386] opened 2017-10-03 12:14 UTC
`about:blank` should behave in a new window the same way it does in a new tab: focus for home pages not content-centric should be moved to the address bar instead of content.

STR:
1. Set home page to `about:blank`
2. Open a new window (CTRL+N)

Result: Focus is on content, requiring a click/F6 to focus the address bar.
Expected: Focus is on the address bar in the new window.

**Comment by JustOff** [comment] 2017-10-03 12:22
Hmm... I can't reproduce this bug on clean profile (27.5.0/27.6.0a1 x32 @ Win7x64).

**Comment by janekptacijarabaci** [comment] 2017-10-03 13:04
I also do not have this problem.

**Comment by wolfbeast** [comment] 2017-10-03 13:18
I can reproduce, on a new install. Currently the behavior is undefined so maybe tit acts differently on Linuxes. Fix is easy though. Please verify that it keeps behaving as expected for you once this is solved.

**Comment by JustOff** [comment] 2017-10-03 13:57
> Please verify that it keeps behaving as expected for you once this is solved.

Nothing has changed for me, everything works just as well as before.

PS: This also had no effect on [Tab Mix Plus issue](https://forum.palemoon.org/viewtopic.php?f=46&t=16876).

**Comment by wolfbeast** [comment] 2017-10-03 13:59
Tab Mix Plus would be an extension issue.

**Comment by wolfbeast** [comment] 2017-10-03 14:00
verified focus now switches to the address bar on a Windows build. Marking this closed.

**Comment by JustOff** [comment] 2017-10-03 14:11
> Tab Mix Plus would be an extension issue.

Yes, definitely, but there was still a small chance that it could be resolved in passing, but the miracle did not happen.

**Comment by wolfbeast** [comment] 2017-11-08 15:19
OK, this is strange -- reported stated it wasn't fixed in 27.6.0, and sure enough, it isn't fixed in the release...
Re-opening.

**Comment by Lorienna** [comment] 2017-11-08 20:39
This is probably regressed by #1310.

#### Steps to reproduce:
1. Launch Pale Moon.
2. In the main menu, select "Options" -> "General".
3. In the __Startup__ section of the "General" tab, choose `Show my windows and tabs from last time`.
4. Either empty the __Home Page__ field or set `about:blank` as a home page there.
5. Click <kbd>OK</kbd> button to save the settings and to close the "Options" window.
6. Press <kbd>Ctrl</kbd> + <kbd>N</kbd> to open a new __non-private__ window.

#### Actual results:
The absence of the text cursor in the address bar.

#### Expected results:
The blinking text cursor in the address bar.

**Comment by wolfbeast** [comment] 2017-11-09 08:14
@Lorienna Good catch on the regression, I think you're right.
The solution in this bug is also incorrect and needs to be backed out; the problem isn't the code opening the window itself, it's the code dealing with session restore states in the newly-opened window.

**Comment by wolfbeast** [comment] 2017-11-09 08:20
More information: The problems ONLY occur if you set the browser to "Restore windows and tabs from last time", otherwise it doesn't -- this would explain why it works properly in a fresh install and in the initial tests, but not when I tested on release (since that's my setting). it may also explain why some people here weren't able to reproduce.
With new windows opened in this state running through the session store init procedure, this needs a different solution for #1310.

**Closed** 2017-11-09 09:12 UTC
Labels: Bug, Front-end, Windows
