### ISSUE TITLE
PaleMoon v27.6.x loses connecticity after heavy network usage in concurrent tabs

### ISSUE THREAD

**Issue by Gpower2** [MoonchildProductions/Pale-Moon#1477] opened 2017-11-17 09:43 UTC
This is definetely not easily reproducable, but since I saw a similar forum thread, I decided to open the issue here, in case other users can provide feedback.

In my case, when opening a lot of tabs with streaming videos, while also having tabs with JS heavy pages, PaleMoon suddenly stops connecting with the network.
Tried with clean profile and disabled security software (I use Avira Free) and the results are the same.
While no error is recorded anywhere, PaleMoon is responding as though the network is disconnected.

The only solution is to close PaleMoon and wait for the process to exit (takes a while while using ~20% CPU with the UI closed)

I would be happy to provide with more feedback, if you can point me to the right direction.

OS: Win10 x64 1709

**Comment by adeshkp** [comment] 2017-11-17 15:52
I'm on Linux and I've seen related behaviour in similar situations. But there is no connectivity drop as such; I just see a few "problem loading page" messages. If I give it some time, things go back normal again (without restart). I generally blame my ISP in theme situations. Or maybe it is congestion in network layer due to too many connections open.

**Comment by wolfbeast** [comment] 2017-11-18 13:48
Pale Moon is conservative in concurrent network connections because of pipelining. With the shift to non-pipelined traffic on many sites (thank you https-everywhere-proponents) we probably need to adjust the caps for open pool connections.

**Comment by wolfbeast** [comment] 2017-11-18 13:51
Could you use some network monitoring tool of choice to see how many open connections Pale Moon maintains in total when you are browsing in a way where it's likely that you run into these issues? That way I can see if it is indeed an issue being close to or at the cap warranting an increase, or if it might be something else?

**Comment by newbthenewbd** [comment] 2017-11-20 20:23
I seem to be affected by this issue as well, under Pale Moon 27.6.1 on Arch Linux.

My browsing model is to open pages in new tabs very frequently (40% of redirects at least, I'd say) and listen to online music on loop, although the issue seems to also appear more frequently after many links are opened in Private Browsing windows. The browser is set to never download cache (or at least so I think, knowing how messy about:config can get), and that probably influences how often the issue appears.

The only extensions installed are uBlock Origin and User Agent Switcher.

Interestingly enough, opening and closing a Private Browsing window without loading anything in it mitigates the issue for a short while after the pages stop loading, but only for the first few times.

**Comment by newbthenewbd** [comment] 2017-11-24 06:33
So, I've done a test using this hopefully reliable one-liner:
```
while :; do lsof -awi -p `pidof palemoon` | grep -c palemoon; sleep 1; done
```
Before I opened a music loop on Newgrounds, the browser worked fine even with 30+ connections reported.

After opening Newgrounds and switching music loops for a while, then replaying one of them about three times, the amount of connections reported stabilized at exactly 21. By that time, it was not possible to open any website.

Once I've used the Ctrl+Shift+P key combination to open a Private Browsing window and closed it, the amount of connections reported immediately changed to 11, and kept changing seemingly randomly. It was also possible to connect to websites again.

Every time the Newgrounds music loop replayed further, the amount of connections reported would stabilize at a value, and the browser wouldn't connect to websites anymore, requiring me to redo the Private Browsing window procedure to keep browsing.

**Comment by wolfbeast** [comment] 2017-11-24 10:11
Well, that doesn't make much sense -- concurrent connections from a pool in Pale Moon release is currently set to 48; you're not hitting that at all. But, please do try to change the values, in case your measuring doesn't catch all of the half-open or loopback connections there may be:

- set `network.http.max-connections` to `256`
- set `network.http.max-connections-per-proxy` to `32`
- restart Pale Moon

**Comment by newbthenewbd** [comment] 2017-11-24 12:10
After setting the values (I assumed that the second one was meant to be `network.http.max-persistent-connections-per-proxy`), I restarted Pale Moon and opened a Newgrounds music loop. It managed to replay about 20 times with zero issues. After that, I've opened a Private Browsing window to check what would happen.

The next time the loop replayed, the browser couldn't connect anymore, while the amount of connections reported was stabilized at merely 14. I opened another Private Browsing window, therefore managing to partially download one of the four tabs trying to connect in the main window. After that, opening and closing further Private Browsing windows wouldn't help anyhow, so I restarted the browser to write this comment.

Perhaps the issue is actually related to the Private Browsing windows messing up something in the memory (for example, through accidental use of thread-unsafe functions), and only gets amplified by the amount of tab-related data in RAM?

**Comment by wolfbeast** [comment] 2017-11-24 12:18
Yes on the corrected value name.

That's most definitely peculiar, but confirms that you're not hitting the cap for connections there. Further complicated by the fact that @Gpower2 isn't using PB windows, as far as I understood; or are you?

**Comment by wolfbeast** [comment] 2017-11-26 14:34
On the off-chance it's a pipelining issue (which would mean your router/connecting network also plays a major role here), see if setting `network.http.pipelining` and `network.http.pipelining.ssl` to `false` and restarting the browser solves this issue or not.

**Comment by Gpower2** [comment] 2017-11-26 16:16
Sorry for the delayed reply, I actually don't use any private browsing windows.
However, I think that this issue might actually be related to #1493 since network connectivity is lost while opening a lot of tabs with playing videos. Since @newbthenewbd also loses connectivity wehn opening a tab with a looped media element, I believe that this might be the cause.

**Comment by newbthenewbd** [comment] 2017-11-27 22:54
Issue still occurs for me after setting `network.http.pipelining` and `network.http.pipelining.ssl` to `false` and restarting the browser.

**Comment by h1z1** [comment] 2017-12-06 16:53
I've only ever hit something like this with broken sites and blocking js.  You wouldn't necessarily see active connections if they were all short.   It's also easy to trigger ddos mitigation on sites as you increase the number of connections.   Pretty silly Mozilla is trying to get rid of pipelining (as of FF54 - June 2017 apparently).

**Comment by wolfbeast** [comment] 2017-12-07 07:52
@h1z1 Mozilla has never liked pipelining; I've personally had lengthy discussions with them about it.

As for the cause of these issues... I don't know. I've seen very similar things lately in other browsers, but only very sporadically, so my guess it's more likely an overall internet health issue (which I predicted would decline!) than anything else, but if anyone has any better information/theory, I'd like to hear it.

**Comment by h1z1** [comment] 2017-12-13 21:47
Common thread may be CDNs.   Maybe like everything they do, it's an attempt to at forced obsolescence in favour of http/2.0 -- aka systemd of http.  Seriously, it has it's own freaking flow control and fingerprinting is part of the damn spec.   

Point is I wouldn't at all be surprised if Google/Mozilla/CDNs were doing nefarious things.

**Comment by wolfbeast** [comment] 2017-12-14 07:48
Let's keep speculation and conspiracies out of this issue and focus on the tech of it, please.

**Comment by Gpower2** [comment] 2018-01-20 12:21
Since v27.7.x this problems seems to be disappeared, HOWEVER, after opening a lot of tabs with lots of media elements (e.g. IndieGoGo product pages) after a while PaleMoon starts to use a lot of CPU with no apparent reason and also uses a lot of RAM. When trying to close it, it stays as a process using lots of CPU for a while before it essentially closes.
I fired up VS while PaleMoon was in this state, and the Debug output repeated the messages:

```
console.error: 
  Message: TypeError: can't access dead object
  Stack:
    getInnerId@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/window/utils.js:78:3
initialize/model.observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker.js:62:27
Observer<.observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/events.js:72:7
```
`[JavaScript Error: "TypeError: aCallback is not a function" {file: "resource://gre/modules/NetUtil.jsm" line: 74}]`
Right before it managed to close, it outputed:
```
1516448974800	Sync.LogManager	ERROR	Failed to cleanup logs: Error: OS.File has been shut down. Rejecting post to DirectoryIterator_prototype_next (resource://gre/modules/osfile/osfile_async_front.jsm:388:28) JS Stack trace: post@osfile_async_front.jsm:388:29 < _next@osfile_async_front.jsm:1367:19 < loop@osfile_async_front.jsm:1341:14 < Handler.prototype.process@Promise-backend.js:867:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:746:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:688:37 < Spinner.prototype.observe@AsyncShutdown.jsm:464:9
[JavaScript Error: "1516448974800	Sync.LogManager	ERROR	Failed to cleanup logs: Error: OS.File has been shut down. Rejecting post to DirectoryIterator_prototype_next (resource://gre/modules/osfile/osfile_async_front.jsm:388:28) JS Stack trace: post@osfile_async_front.jsm:388:29 < _next@osfile_async_front.jsm:1367:19 < loop@osfile_async_front.jsm:1341:14 < Handler.prototype.process@Promise-backend.js:867:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:746:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:688:37 < Spinner.prototype.observe@AsyncShutdown.jsm:464:9" {file: "resource://gre/modules/Log.jsm" line: 749}]

```

Unfortunately I couldn't manage to debug further and it's not the easiest behavior to reproduce, hopefully the above messages could give you a hint.

**Comment by wolfbeast** [comment] 2018-03-27 10:07
> Since v27.7.x this problems seems to be disappeared

Then I'll consider this resolved for now. Please open a new issue if there's more occurrences of this and more definitive information about what exactly happens in your situation.
Also please open a new issue for unrelated things like CPU usage.

**Closed by wolfbeast** 2018-03-27 10:07 UTC
Labels: More Info Needed
