### ISSUE TITLE
Pale Moon v26.xx breaks compatibility mith many download related Firefox extensions

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#351] opened 2016-02-07 11:43 UTC
Many download related extensions are now incompatible with Pale Moon, because they use the version number "26" to detect the browsers compatibility.
One example is the 'Download Flash & Video' extension..
The problem with the code was discovered by jumba, and posted in the Pale Moon forum here:
http://forum.palemoon.org/viewtopic.php?f=46&t=10849#p77365

**Comment by wolfbeast** [comment] 2016-02-07 11:52
And how do you expect we fix all the download related extensions on the browser side if they do arbitrary version checks?

This will have to be addressed in the extensions themselves by actually targeting Pale Moon in their detection logic. Either by the original authors, or by forking the extensions.

**Comment by THEtomaso** [comment] 2016-02-07 11:57
I was just hoping that it would be possible to add some kind of a workaround in PM's code.
There are now a lot of incompatible Firefox extensions because of this, and unfortunately I don't think that many of their developers will care about the problem.
I really wish that it wasn't so, but that's the sad reality of it.

**Comment by wolfbeast** [comment] 2016-02-07 12:02
The reality is also that apart from sticking Pale Moon's main version number to something lower, there isn't a way to work around this. Our compatibility with Firefox extensions only goes so far and building in elaborate workarounds with dual version numbers is not only impractical, it's also impossible since extensions, by design, get native access to JS interfaces.

So, the sad reality is that over time, extensions will become less compatible with us. It's inevitable.
If developers don't care about catering to a browser where their extensions still have a future (since Firefox will drop "legacy extensions"), then that is their choice. And it's their choice leading to user disappointment in that case.
Another reality is that even though I (and Tobin) would like to, *we* can't possibly take over extension development.

**Comment by wolfbeast** [comment] 2016-04-18 19:48
Considering this is something that needs extension changes unless we'd want to implement more shims than we already have, I'm closing this.

**Closed by wolfbeast** 2016-04-18 19:48 UTC
Labels: Extensions
