### ISSUE TITLE
GitHub commit hash clipboard button does not work

### ISSUE THREAD

**Issue by MingcongBai** [MoonchildProductions/Pale-Moon#761] opened 2016-12-08 18:34 UTC
How to reproduce:

- Open up a commit history page in GitHub, for instance, https://github.com/scopatz/nanorc/commits/master.
- Click on the "Copy the Full SHA" button beside the short hash displayed.
- Nothing is copied to the clipboard.

System environment:

- AOSC OS (Linux)
- AMD64, and PowerPC 64-bit (Big Endian)
- Pale Moon version 27.0.2

**Comment by Capostrophic** [comment] 2016-12-09 00:31
Yep. A regression I believe.

**Comment by wolfbeast** [comment] 2016-12-09 02:12
Well, if anyone has an idea what might be the cause, that would be great.

**Comment by janekptacijarabaci** [comment] 2016-12-09 06:05
AFAIK - This is the same problem as: https://github.com/MoonchildProductions/Pale-Moon/issues/479#issuecomment-246589884

**Comment by wolfbeast** [comment] 2016-12-09 10:23
Thanks @janekptacijarabaci -- looks like that's it.

Right, so, Mozilla removed CAPS functionality in Firefox 29, and had non-functional clipboard copy/cut commands until Firefox 41 because they never bothered to implement the replacement spec. XD
GitHub probably recently changed their code to use FF41+ solutions instead of Flash-based like before.

To fix this, and potentially #479 in one go, this would need 3 bugs on BMO ported (should be relatively straight-forward).
- [ ] Bug 1162952 and
- [ ] Bug 1159490 first, then 
- [ ] Bug 1012662

**Comment by wolfbeast** [comment] 2016-12-19 15:43
Putting in the clipboard API changes fixes it on all other sites but not GitHub. They must be doing something else as well.

**Comment by janekptacijarabaci** [comment] 2016-12-19 16:28
That function is here:
![1](https://cloud.githubusercontent.com/assets/2373486/21320226/8be92272-c610-11e6-8697-03b5b448d2e0.png)

**Comment by wolfbeast** [comment] 2016-12-19 16:32
If I check the dom it's n't attached to the button though.

**Comment by janekptacijarabaci** [comment] 2016-12-19 16:55
But still valid (for this button):
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=f986e55c4e0b&tochange=45a4d6336c73
Firefox 41.0a1 (2015-05-29) - does not work
Firefox 41.0a1 (2015-05-30) - works

**Comment by wolfbeast** [comment] 2016-12-19 17:04
That doesn't help because that it the change for the clipboard API that I implemented. It's something else that must have been changed before that point in time that GitHub explicitly relies on.

**Comment by janekptacijarabaci** [comment] 2016-12-19 18:01
However, the problem is here:

__Pale Moon__
```
<html lang="en" class="">
```
vs.

__Firefox__
```
<html lang="en" class=" is-copy-enabled">
```

If you change it, it works.

**Comment by janekptacijarabaci** [comment] 2016-12-19 18:49
I suggest adding: https://bugzilla.mozilla.org/show_bug.cgi?id=1170911

**Comment by wolfbeast** [comment] 2016-12-19 21:09
And.. why exactly is Github giving Firefox a different tag in their HTML a browser bug?
Also, your suggestion has nothing to do with making this work. It's just a pref so people can disable it again if they don't want it That should be a separate issue.

**Comment by wolfbeast** [comment] 2016-12-19 21:20
OK, I've checked the behavior -- in 27.0.3, setting the class creates an ugly SHA text in the actual page. Not entirely sure what trickery GitHub uses and for what browsers it does so, but that's clearly not intended ;)
With the clipboard API changes that I've put in, and adding the class to the HTML document, everything works as-intended.

So... we need to know what GitHub specifically does to add this class to the HTML, and why the API being present isn't feature-detected to enable it when available... Time to ask GH support for assistance/a solution.

**Comment by wolfbeast** [comment] 2017-01-06 14:40
Answer from GH staff:

>You're right about the User-Agent test for this feature. We prefer to do feature detection instead, so features work as soon as the browser supports them. In this case, we needed to work around `queryCommandSupported` implementations returning false positives.
>I removed the User-Agent test so clipboard copy should be working now. Let me know if there's anything else I can do to help.

So if all goes well this should work in 27.1 now.

**Comment by wolfbeast** [comment] 2017-01-06 14:57
As an aside, the functionality already works **partially** in 27.0.3 - if you click the button, the hash is overlaid on the page and automatically selected -- pressing Ctrl+C after clicking the button will copy the full hash to clipboard. This is a workaround for now. On trunk it's been verified to work proper without overlay.

**Comment by wolfbeast** [comment] 2017-01-12 12:30
The unstable channel should have a working setup now, considering GH also changed it server-side with removal of the UA test for this feature.
Can someone verify so this can be closed?

**Comment by JustOff** [comment] 2017-01-12 12:33
Works for me.

**Comment by wolfbeast** [comment] 2017-01-12 12:57
Perfect. Closing.

**Closed by wolfbeast** 2017-01-12 12:57 UTC
Labels: Regression, Verification Needed
