### ISSUE TITLE
Pictures in VK become invisible after the preference to override the page colors is set to "Always"

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1007] opened 2017-04-06 13:12 UTC
In VK pictures become invisible after the preference to override the page colors is set to "Always". This affects mainly the photo/video album pages and the wall posts, and a fresh browser profile doesn't help.

Apparently, all Mozilla-based builds for Windows desktop since at least version 3.6.* are affected, but it's unclear about any other builds for any other OS.

---

<b>Steps to reproduce:</b>

1. Open a wall post containing a picture:
https://vk.com/wall-23300841_225128

2. Open an album page containing a lot of pictures:
https://vk.com/albums-23300841

3. In the "Options" menu of the browser, select:
Content  =>  Colors  =>  "Override the colors specified by the page with my selections above"  => Always.
* Alternatively, in <tt>about:config</tt> set <tt>browser.display.document_color_use</tt> to <tt>2</tt>.
 
<b>FYI:</b> In the builds v3.6.*, <tt>browser.display.use_document_colors</tt> should be set to <tt>false</tt> to achieve the same effect, and a mere checkbox to turn it on/off in the menu is present.

<b>Actual results:</b>
The colors are changed, and the pictures are invisible.

<b>Expected results:</b>
The colors are changed, and the pictures are visible.
Also, it'd be great if the preference in question was on a per-site basis. :)

---

If this is confirmed as a bug and resolved, <b>someone please report it to Bugzilla, together with the issue #996</b>, since I'm not sure how to do this properly. Thank you in advance.

And thanks to everyone who contributed to fix the issue #996! :+1:

**Comment by janekptacijarabaci** [comment] 2017-04-06 13:47
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1279729

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=639134
However the following is not implemented:
https://hg.mozilla.org/mozilla-central/rev/460d573b8822#l1.14
(is it deliberately so?)

**Comment by wolfbeast** [comment] 2017-04-06 13:53
The setting is a setting for accessibility -- it is meant to be used only by people who need specific colors to be able to read websites. This is why it is not a per-site setting.

@janekptacijarabaci what is not implemented? We have the tristate setup.

**Comment by wolfbeast** [comment] 2017-04-06 14:01
A quick looks shows that the images that vanish are set as background-images instead of image elements. That would be by design, in that case, since overriding colors will also override background images of elements. This is required because of the common use of background images in paragraph displays to set a patterned background "color". if these images were not overridden, it would result in an unreadable page.

The way VK uses background images to display actual photos (they shouldn't use background images for foreground visual elements!) is incompatible with this accessibility override.

**Comment by janekptacijarabaci** [comment] 2017-04-06 14:06
> what is not implemented? We have the tristate setup.

Ad 
https://github.com/MoonchildProductions/Pale-Moon/blob/27.2.1_Release/browser/components/migration/IEProfileMigrator.js#L530
```
              "browser.display.use_document_colors",
              function (v) !Boolean(v));
```

vs.

```
              "browser.display.document_color_use",
              function (v) !Boolean(v) ? 0 : 2);
```

**Comment by wolfbeast** [comment] 2017-04-06 14:07
The formulae are displayed correctly with color overrides. They are, however, SVG images -- if you are using an inverted color scheme, then they will become black on black and you won't see them (because of transparency).

**Comment by wolfbeast** [comment] 2017-04-06 14:08
Ah, the migrator -- no that's not on purpose; it simply wasn't taken into account when doing the platform update. That's a minor bug unrelated to this issue; feel free to patch it.

**Comment by Lorienna** [comment] 2017-04-06 17:42
But there are a lot of web-sites with a bad design, which are difficult to read due to that, and I actually use this preference on the daily basis...

Also, sometimes this allows to see hidden links, previously blended into the background with the help of the page's original colors.

**Comment by wolfbeast** [comment] 2017-04-06 21:12
If bad design makes pages when displayed as-intended difficult to read, then that is feedback you should give to the webmasters of those sites. It's not a browser's task to try and mitigate bad design -- it is a browser's task to display sites as close to as-designed as possible, regardless of how good or bad the design is.

Once again, overriding the colors on websites is mainly an accessibility feature; it will not work with all designs out there. I'm keeping an eye on the BMO bug, but otherwise will close this issue as wontfix since any compromise on how much gets overridden will take away from its original purpose.

**Closed by wolfbeast** 2017-04-06 21:12 UTC

**Comment by Lorienna** [comment] 2017-04-06 21:52
Ok, thanks for your help anyway.
