### ISSUE TITLE
Google AMP pages are unable to report back user identification ; likely related to incomplete promise support.

### ISSUE THREAD

**Issue by hkmaly** [MoonchildProductions/Pale-Moon#416] opened 2016-04-05 20:17 UTC
See https://github.com/ampproject/amphtml/issues/2822 which I created and only while doing it realized that AMP is not only beta thing involved. Basically, AMP is somehow using promise ( based on https://github.com/ampproject/amphtml/pull/2509 ) to fill user identification into urls and then resolving them and it's quitely failing.

I hope you will be able to get what exactly is the issue either from AMP sources or the AMP team.

**Comment by wolfbeast** [comment] 2016-04-05 22:34
Duplicate of #360

**Closed by wolfbeast** 2016-04-05 22:34 UTC
Labels: Duplicate

**Comment by hkmaly** [comment] 2016-04-08 22:46
According to amp project developer in linked bug, they are polyfilling if promise is completely off. Any ideas what can go wrong with that?

**Comment by wolfbeast** [comment] 2016-04-09 00:25
No, because we don't have any content-exposed promises at all. So if their code is doing what it is supposed to be doing, then it should polyfill for us.
(dom.promise.enabled is off by default in Pale Moon - and it should remain off because the current implementation is not spec compliant and won't work as a result)
