### ISSUE TITLE
Crash if pulse audio cannot be loaded

### ISSUE THREAD

**Issue by h1z1** [MoonchildProductions/Pale-Moon#817] opened 2017-01-09 20:14 UTC
For some reason I cannot update #222 Palemoon PulseAudio integration implementation (You can't comment at this time)?.   

Still remains as of the latest mainline (27.0.3) and git (27.1.0b1) versions.  Recompiling without pulse works around it.

**Comment by wolfbeast** [comment] 2017-01-11 11:41
If you don't have pulseaudio on your system, then don't compile with it.

**Comment by wolfbeast** [comment] 2017-01-11 12:28
Duplicate of #222

**Closed by wolfbeast** 2017-01-11 12:28 UTC
Labels: Duplicate, Linux
