### ISSUE TITLE
Post-implementation notes of ffmpeg playback

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#533] opened 2016-09-22 17:58 UTC
As discussed with @trav90 and following on some of the prep work, we are planning to implement ffmpeg. This is mostly a tracking bug for after implementing ffmpeg to collect tasks to be performed for this that might otherwise be forgotten after the main implementation is done.

Noted code changes that should be added post implementation:
- [ ] https://hg.mozilla.org/mozilla-central/rev/e734cf260908 (crash fix: bounds check for sizes)
- [X] ~~https://hg.mozilla.org/releases/mozilla-beta/rev/11ba9af07367 (depending on BMO 1171330 - if that is implemented, this fix should be applied on top)~~
- [X] ~~https://hg.mozilla.org/releases/mozilla-esr45/rev/893de7431d51a2a3579762ff70c5e6ef0ae96628 (crash fix due to racey constructor/destructor pair in MFR, depending on 1172264)~~

If there are known implementation bugs for ffmpeg that have been addressed in FF, please comment so they can be added.

**Comment by trav90** [comment] 2016-09-22 20:22
Please assign this to me.

**Comment by wolfbeast** [comment] 2016-11-17 01:15
In your porting across of patches, did you also have BMO 1171330 in there somewhere?

**Comment by trav90** [comment] 2016-11-17 02:16
No, because it is for MSE support and is not a blocker to get ffmpeg working. Between crashes and broken YouTube with newer GStreamer versions on Tycho, getting ffmpeg working has been my top priority. Once we can drop GStreamer for MP4 video (and I do believe I am getting close), I do plan to go back and port bugs (including this one among others) that will further improve our MSE support.

**Comment by wolfbeast** [comment] 2016-11-17 13:26
OK, updated the notes with the relevant commit that should be ported on top.

**Comment by trav90** [comment] 2016-11-29 05:51
Looking at the "crash fix: bounds check for sizes" HG commit above, it only applies to VP9 decoding with FFmpeg (or ffvpx). The ffvpx headers are not currently in our tree, so this fix is N/A unless we want to use FFmpeg for VP8/VP9 decoding as well. Mozilla claims that ffvpx is considerably faster than libvpx is (see BMO bugs [1197319](https://bugzilla.mozilla.org/show_bug.cgi?id=1197319) & [1210219](https://bugzilla.mozilla.org/show_bug.cgi?id=1210219)).

@wolfbeast @mattatobin is this something we want?

**Comment by trav90** [comment] 2016-12-05 21:39
As discussed with @wolfbeast on Jabber, I will be enabling ffvpx on Linux. Once we have a working implementation on Linux, we will evaluate if we want to use it for Windows as well.

**Comment by wolfbeast** [comment] 2016-12-13 16:14
Added a third commit that should be ported because of a crash (protected bug). This applies to 27.1 but not to 27.0.3 since we don't have the MFR there yet.

**Comment by trav90** [comment] 2016-12-14 04:49
The racey condition listed above was caused by BMO 1172264 which has not been ported over, so that commit shouldn't apply to us.

**Comment by wolfbeast** [comment] 2017-01-21 18:34
How are we on this, I recall you addressing at least some of this; Are these points resolved?

**Comment by trav90** [comment] 2017-01-21 19:14
Point 1 is N/A (we don't use the whole FFmpeg source code, only applicable headers). Mozilla bundles the whole code in their tree because they use FFmpeg for VP8/9 decoding on Windows. 

Point 2 is also N/A - The issue that this patch fixes was introduced into Mozilla's tree in bug 1171330 when they rewrote the sourcebuffer/trackbuffer portion of their MSE code. That bug has not been ported to our tree.

Point 3 is N/A - the condition that patch fixes was introduced in Mozilla's tree by bug 1172264 which also has not been ported to our tree.

**Comment by wolfbeast** [comment] 2017-01-21 20:50
Point 1 is for ffvpx, and you've said above that ffvpx is used on Linux, so how can that be N/A then?

**Comment by trav90** [comment] 2017-01-22 05:26
Mozilla includes and compiles the FFmpeg source code within their tree for use on Windows. As a result, Firefox by default uses a built-in version of FFmpeg cross-platform (they pull new versions from upstream semi-regularly). 

We only include the minimal headers needed to support FFmpeg (libavcodec & libavutil specifically). We don't support FFmpeg/ffvpx on Windows, and on Linux we use the system installed FFmpeg/ffvpx (if Pale Moon can't find libavcodec on the system, FFmpeg won't be used).

Firefox is affected by sec issues and crashes within FFmpeg due to it being compiled into their binaries. The hg commit in point 1 doesn't affect Mozilla code, it's a crash fix that was deemed important enough to cherry pick from upstream before they updated their in-tree FFmpeg to the latest version.

Since we don't include the full FFmpeg source and use the system-installed version instead, we don't need to import any fixes directly from FFmpeg (such as the one above). They'll be released/backported into the various distros by their respective package maintainers, and installed by users as they update their systems.

**Comment by trav90** [comment] 2017-01-22 05:29
Also, if we do get to where we bundle the current FFmpeg source in our tree in the same way Mozilla does, I'll import the newest version (currently 3.2.2) which will already include all the fixes that have been made by FFmpeg (including the one in point 1).

**Comment by wolfbeast** [comment] 2017-01-22 06:41
Crystal clear! Thanks for the status update -- also explains why playing movs wasn't hooked up in Windows ;)

No reason to keep this open then.

**Closed** 2017-01-22 06:42 UTC
Labels: Linux

**Comment by mattatobin** [comment] 2017-01-23 13:21
Reminder: Bundling ffmpeg is only possible legally if it is compiled to it's own lib.. If it is folded in with libxul then there will be a serious conflict between gpl/lgpl/mpl points. So yeah, it would be awesome to have it but it will have to live as it's own lib/dll file not gkmedias and not libevil.

**Comment by wolfbeast** [comment] 2017-01-23 14:40
I thought ffmpeg was **LGPL**, not GPL, in which case it's fine as long as it's mentioned in the license file (we already have LGPL modules in the browser that way like libsoundtouch and libav). Also, simply splitting it out into its own dll I think would _not_ satisfy the GPL if it's still distributed with it as (integral) part of a larger work.

Considering all this, I'm pretty sure we're in the clear here, but double-checking is always good ;) Thanks for the reminder.

**Comment by wolfbeast** [comment] 2017-01-23 15:02
Verified that linking as a shared library does **not** satisfy the GPL:

> When a program is linked with a library, **whether statically or using a shared library**, the combination of the two is legally speaking a combined work, a derivative of the original library. The ordinary General Public License therefore permits such linking only if the entire combination fits its criteria of freedom. The Lesser General Public License permits more lax criteria for linking other code with the library.
